// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HyperlinkCustomField - Reference to a custom field, as in the object itself, and not any particular value.
type HyperlinkCustomField struct {
	Id RTID `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Type *ConstantCustomField `json:"type,omitempty"`
}
