// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HyperlinkSelf - Link to self. Type will vary depending on where you got this from.
type HyperlinkSelf struct {
	Id RTID `json:"id,omitempty"`
	Type *TypeEnum `json:"type,omitempty"`
}
