// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldsAppliedInner - CustomFieldsAppliedInner struct
type CustomFieldsAppliedInner struct {
	Id RTID `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Ref string `json:"ref,omitempty"`
	Type *ConstantCustomField `json:"type,omitempty"`
	Url string `json:"_url,omitempty"`
}
