// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LifecycleConfigurationActionsInner - LifecycleConfigurationActionsInner struct
type LifecycleConfigurationActionsInner struct {
}
