// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldReference - A reference to a custom field
type CustomFieldReference struct {
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
