// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HyperlinkRights - Link to an object's rights, or to the rights that can be granted on it. Carries no id of its own.
type HyperlinkRights struct {
}
