// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QueueIdNameGet200ResponseAllOfHyperlinksInner - QueueIdNameGet200ResponseAllOfHyperlinksInner struct
type QueueIdNameGet200ResponseAllOfHyperlinksInner struct {
	Ref string `json:"ref,omitempty"`
	Url string `json:"_url,omitempty"`
	Type *TypeEnum `json:"type,omitempty"`
	Id RTID `json:"id,omitempty"`
}
