// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LifecycleNameValidatePost200Response - LifecycleNameValidatePost200Response struct
type LifecycleNameValidatePost200Response struct {
	Valid *bool `json:"valid,omitempty"`
	Warnings []string `json:"warnings,omitempty"`
}
