// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TicketIdPutRequest - TicketIdPutRequest struct
type TicketIdPutRequest struct {
	CustomFields map[string]CustomFieldsUploadCustomFieldsValue `json:"CustomFields,omitempty"`
	DependsOn *TicketLink `json:"DependsOn,omitempty"`
	Child *TicketLink `json:"Child,omitempty"`
	ReferredToBy *TicketLink `json:"ReferredToBy,omitempty"`
	Parent *TicketLink `json:"Parent,omitempty"`
	DependedOnBy *TicketLink `json:"DependedOnBy,omitempty"`
	RefersTo *TicketLink `json:"RefersTo,omitempty"`
	Subject string `json:"Subject,omitempty"`
	Owner string `json:"Owner,omitempty"`
	Requestor string `json:"Requestor,omitempty"`
	Cc string `json:"Cc,omitempty"`
	AdminCc string `json:"AdminCc,omitempty"`
	Starts string `json:"Starts,omitempty"`
	Due string `json:"Due,omitempty"`
	Priority string `json:"Priority,omitempty"`
	Status string `json:"Status,omitempty"`
	Queue string `json:"Queue,omitempty"`
}
