// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TicketIdGet200ResponseAllOfHyperlinksInner - TicketIdGet200ResponseAllOfHyperlinksInner struct
type TicketIdGet200ResponseAllOfHyperlinksInner struct {
	Ref string `json:"ref,omitempty"`
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Type *TypeEnum `json:"type,omitempty"`
	From string `json:"from,omitempty"`
	To string `json:"to,omitempty"`
	Update string `json:"update,omitempty"`
	Label string `json:"label,omitempty"`
}
