// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CatalogPostRequest - CatalogPostRequest struct
type CatalogPostRequest struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Lifecycle string `json:"Lifecycle,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
}
