// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UserIdNamePutRequest - UserIdNamePutRequest struct
type UserIdNamePutRequest struct {
	CustomFields map[string]CustomFieldsUploadCustomFieldsValue `json:"CustomFields,omitempty"`
	RealName string `json:"RealName,omitempty"`
	NickName string `json:"NickName,omitempty"`
	EmailAddress string `json:"EmailAddress,omitempty"`
	Gecos string `json:"Gecos,omitempty"`
	Lang string `json:"Lang,omitempty"`
	Timezone string `json:"Timezone,omitempty"`
	FreeformContactInfo string `json:"FreeformContactInfo,omitempty"`
	Comments string `json:"Comments,omitempty"`
	WorkPhone string `json:"WorkPhone,omitempty"`
	MobilePhone string `json:"MobilePhone,omitempty"`
	HomePhone string `json:"HomePhone,omitempty"`
	PagerPhone string `json:"PagerPhone,omitempty"`
	Organization string `json:"Organization,omitempty"`
	Address1 string `json:"Address1,omitempty"`
	Address2 string `json:"Address2,omitempty"`
	City string `json:"City,omitempty"`
	Zip string `json:"Zip,omitempty"`
	State string `json:"State,omitempty"`
	Country string `json:"Country,omitempty"`
	Name string `json:"Name,omitempty"`
	Disabled string `json:"Disabled,omitempty"`
	Privileged int64 `json:"Privileged,omitempty"`
}
