// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AssetPostRequest - AssetPostRequest struct
type AssetPostRequest struct {
	CustomFields map[string]CustomFieldsUploadCustomFieldsValue `json:"CustomFields,omitempty"`
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Catalog string `json:"Catalog,omitempty"`
	Status string `json:"Status,omitempty"`
	Owner string `json:"Owner,omitempty"`
	HeldBy []string `json:"HeldBy,omitempty"`
	Contact []string `json:"Contact,omitempty"`
}
