// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldApplication - One place a custom field applies. ObjectId 0 with Global true is the global application; anything else names the object.
type CustomFieldApplication struct {
	ObjectId int32 `json:"ObjectId,omitempty"`
	Global *bool `json:"Global,omitempty"`
	ObjectType string `json:"ObjectType,omitempty"`
	ObjectName string `json:"ObjectName,omitempty"`
	Url string `json:"_url,omitempty"`
}
