// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ClassPostRequest - ClassPostRequest struct
type ClassPostRequest struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
}
