// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GroupIdPutRequest - GroupIdPutRequest struct
type GroupIdPutRequest struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Disabled string `json:"Disabled,omitempty"`
}
