// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HyperlinkCreate - Operation to create a ticket
type HyperlinkCreate struct {
	Type string `json:"type,omitempty"`
}
