// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PrincipalReference - A principal as a RIGHTS listing spells it, which is not how the rest of the API spells one. `GET /global/rights` answers `{\"id\":6,\"_url\":\"...\"}` -- the id unquoted, and no `type` at all.
type PrincipalReference struct {
	Id RTID `json:"id,omitempty"`
	Name string `json:"Name,omitempty"`
	Url string `json:"_url,omitempty"`
}
