// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LifecycleConfiguration - A lifecycle's whole configuration. RT spells these keys in lower case, unlike every other object in this API.
type LifecycleConfiguration struct {
	Type string `json:"type,omitempty"`
	Initial []string `json:"initial,omitempty"`
	Active []string `json:"active,omitempty"`
	Inactive []string `json:"inactive,omitempty"`
	Defaults map[string]string `json:"defaults,omitempty"`
	Transitions map[string][]string `json:"transitions,omitempty"`
	Rights map[string]string `json:"rights,omitempty"`
	Actions []LifecycleConfigurationActionsInner `json:"actions,omitempty"`
	Colors map[string]string `json:"colors,omitempty"`
}
