// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFields - An object with customfields in a response
type CustomFields struct {
	CustomFields []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
}
