// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ClassesAllGet200Response - ClassesAllGet200Response struct
type ClassesAllGet200Response struct {
	Page int32 `json:"page,omitempty"`
	Pages int32 `json:"pages,omitempty"`
	PerPage int32 `json:"per_page,omitempty"`
	Count int32 `json:"count,omitempty"`
	Total int32 `json:"total,omitempty"`
	Items []ClassReference `json:"items,omitempty"`
}
