// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ObjectType - Object containing type field.
type ObjectType struct {
	Type *TypeEnum `json:"type,omitempty"`
}
