// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TicketPropertiesUploadCommon - Properties shared with ticket creation and update operations.
type TicketPropertiesUploadCommon struct {
	Subject string `json:"Subject,omitempty"`
	Owner string `json:"Owner,omitempty"`
	Requestor string `json:"Requestor,omitempty"`
	Cc string `json:"Cc,omitempty"`
	AdminCc string `json:"AdminCc,omitempty"`
	Starts string `json:"Starts,omitempty"`
	Due string `json:"Due,omitempty"`
	Priority string `json:"Priority,omitempty"`
	Status string `json:"Status,omitempty"`
}
