// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GroupIdGet200ResponseAllOfMembersInner - GroupIdGet200ResponseAllOfMembersInner struct
type GroupIdGet200ResponseAllOfMembersInner struct {
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
