// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldValuePropertiesCommon - One of the values a Select or Combobox custom field offers.
type CustomFieldValuePropertiesCommon struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Category string `json:"Category,omitempty"`
}
