// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QueuePostRequest - These are the properties shown in the UI. Others could be accepted here as well.
type QueuePostRequest struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Lifecycle string `json:"Lifecycle,omitempty"`
	SubjectTag string `json:"SubjectTag,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	CorrespondAddress string `json:"CorrespondAddress,omitempty"`
	CommentAddress string `json:"CommentAddress,omitempty"`
	SLADisabled string `json:"SLADisabled,omitempty"`
	Disabled string `json:"Disabled,omitempty"`
}
