// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomfieldIdGet200ResponseAllOfHyperlinksInner - CustomfieldIdGet200ResponseAllOfHyperlinksInner struct
type CustomfieldIdGet200ResponseAllOfHyperlinksInner struct {
	Ref string `json:"ref,omitempty"`
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
