// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TicketIdGet200Response - TicketIdGet200Response struct
type TicketIdGet200Response struct {
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	CustomFields []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
	Queue *QueueReference `json:"Queue,omitempty"`
	Owner *UserReference `json:"Owner,omitempty"`
	Starts string `json:"Starts,omitempty"`
	Started string `json:"Started,omitempty"`
	EffectiveId *TicketReference `json:"EffectiveId,omitempty"`
	Resolved string `json:"Resolved,omitempty"`
	Due string `json:"Due,omitempty"`
	Subject string `json:"Subject,omitempty"`
	TimeEstimated string `json:"TimeEstimated,omitempty"`
	TimeWorked string `json:"TimeWorked,omitempty"`
	TimeLeft string `json:"TimeLeft,omitempty"`
	InitialPriority string `json:"InitialPriority,omitempty"`
	Priority string `json:"Priority,omitempty"`
	FinalPriority string `json:"FinalPriority,omitempty"`
	Requestor []UserReference `json:"Requestor,omitempty"`
	Cc []interface{} `json:"Cc,omitempty"`
	AdminCc []interface{} `json:"AdminCc,omitempty"`
	Type string `json:"Type,omitempty"`
	Status string `json:"Status,omitempty"`
	Hyperlinks []TicketIdGet200ResponseAllOfHyperlinksInner `json:"_hyperlinks,omitempty"`
}
