// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// JustMessage - Just a message. This is often used in errors.
type JustMessage struct {
	Message string `json:"message,omitempty"`
}
