// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HyperlinkLifecycle - A possible transition in the objects state.
type HyperlinkLifecycle struct {
	From string `json:"from,omitempty"`
	To string `json:"to,omitempty"`
	Update string `json:"update,omitempty"`
	Label string `json:"label,omitempty"`
}
