// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomfieldIdAppliestoPostRequest - CustomfieldIdAppliestoPostRequest struct
type CustomfieldIdAppliestoPostRequest struct {
	ObjectId int32 `json:"ObjectId,omitempty"`
}
