// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RightsListAllOfItems - RightsListAllOfItems struct
type RightsListAllOfItems struct {
	Right string `json:"Right,omitempty"`
	Group *PrincipalReference `json:"Group,omitempty"`
	User *PrincipalReference `json:"User,omitempty"`
}
