// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RightGrant - One right, granted to one principal. Exactly one of Group and User is given.
type RightGrant struct {
	Right string `json:"Right,omitempty"`
	Group string `json:"Group,omitempty"`
	User string `json:"User,omitempty"`
}
