// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomfieldIdGet200Response - CustomfieldIdGet200Response struct
type CustomfieldIdGet200Response struct {
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	Name string `json:"Name,omitempty"`
	Type string `json:"Type,omitempty"`
	RenderType string `json:"RenderType,omitempty"`
	LookupType string `json:"LookupType,omitempty"`
	ValidationHint string `json:"ValidationHint,omitempty"`
	Description string `json:"Description,omitempty"`
	EntryHint string `json:"EntryHint,omitempty"`
	UniqueValues *PerlBoolean `json:"UniqueValues,omitempty"`
	Pattern string `json:"Pattern,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
	Values []string `json:"Values,omitempty"`
	Hyperlinks []CustomfieldIdGet200ResponseAllOfHyperlinksInner `json:"_hyperlinks,omitempty"`
	MaxValues string `json:"MaxValues,omitempty"`
}
