// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LifecyclesPostRequest - LifecyclesPostRequest struct
type LifecyclesPostRequest struct {
	Name string `json:"Name,omitempty"`
	Type string `json:"Type,omitempty"`
}
