// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QueueIdNameRightsPost201Response - QueueIdNameRightsPost201Response struct
type QueueIdNameRightsPost201Response struct {
	Right string `json:"Right,omitempty"`
	Group *PrincipalReference `json:"Group,omitempty"`
	User *PrincipalReference `json:"User,omitempty"`
}
