// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QueueIdNameRightsBulkPost200Response - QueueIdNameRightsBulkPost200Response struct
type QueueIdNameRightsBulkPost200Response struct {
	Granted []RightsBulkOutcome `json:"granted,omitempty"`
	Revoked []RightsBulkOutcome `json:"revoked,omitempty"`
}
