// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ArticlePropertiesCommon - Properties of an article.
type ArticlePropertiesCommon struct {
	Name string `json:"Name,omitempty"`
	Summary string `json:"Summary,omitempty"`
	Class string `json:"Class,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Parent int32 `json:"Parent,omitempty"`
	URI string `json:"URI,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
}
