// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TypelessGenericObject - A generic object with type field missing. Add it in other templates.
type TypelessGenericObject struct {
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
}
