// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PerlBoolean - RT doesn't bother to translate perl boolean value to JSON.
type PerlBoolean struct {
}
