// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GroupPostRequest - These are just the properties which can be set from the UI. Dont know about others.
type GroupPostRequest struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
}
