// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UserPassword - Optionanl password property for a user object
type UserPassword struct {
	Password string `json:"Password,omitempty"`
}
