// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GenericObject - A generic object thats used in many API endpoints. Refer this within suitable schemas. Note that there are strictly typed versions of this too.
type GenericObject struct {
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
