// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UserReference - A reference to a user.
type UserReference struct {
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
