// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RightsBulk - Rights to grant and to revoke in one request.
type RightsBulk struct {
	Grant []RightGrant `json:"grant,omitempty"`
	Revoke []RightGrant `json:"revoke,omitempty"`
}
