// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomfieldIdValueIdGet200Response - CustomfieldIdValueIdGet200Response struct
type CustomfieldIdValueIdGet200Response struct {
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Category string `json:"Category,omitempty"`
}
