// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ArticleIdGet200Response - ArticleIdGet200Response struct
type ArticleIdGet200Response struct {
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	CustomFields []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
	Name string `json:"Name,omitempty"`
	Summary string `json:"Summary,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Class *ClassReference `json:"Class,omitempty"`
	Parent *ArticleIdGet200ResponseAllOfParent `json:"Parent,omitempty"`
	URI string `json:"URI,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
}
