// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TicketLinksUpload - Ticket links when creating or updating a ticket.
type TicketLinksUpload struct {
	DependsOn *TicketLink `json:"DependsOn,omitempty"`
	Child *TicketLink `json:"Child,omitempty"`
	ReferredToBy *TicketLink `json:"ReferredToBy,omitempty"`
	Parent *TicketLink `json:"Parent,omitempty"`
	DependedOnBy *TicketLink `json:"DependedOnBy,omitempty"`
	RefersTo *TicketLink `json:"RefersTo,omitempty"`
}
