// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UserIdNameGet200Response - UserIdNameGet200Response struct
type UserIdNameGet200Response struct {
	CustomFields []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	RealName string `json:"RealName,omitempty"`
	NickName string `json:"NickName,omitempty"`
	EmailAddress string `json:"EmailAddress,omitempty"`
	Gecos string `json:"Gecos,omitempty"`
	Lang string `json:"Lang,omitempty"`
	Timezone string `json:"Timezone,omitempty"`
	FreeformContactInfo string `json:"FreeformContactInfo,omitempty"`
	Comments string `json:"Comments,omitempty"`
	WorkPhone string `json:"WorkPhone,omitempty"`
	MobilePhone string `json:"MobilePhone,omitempty"`
	HomePhone string `json:"HomePhone,omitempty"`
	PagerPhone string `json:"PagerPhone,omitempty"`
	Organization string `json:"Organization,omitempty"`
	Address1 string `json:"Address1,omitempty"`
	Address2 string `json:"Address2,omitempty"`
	City string `json:"City,omitempty"`
	Zip string `json:"Zip,omitempty"`
	State string `json:"State,omitempty"`
	Country string `json:"Country,omitempty"`
	Name string `json:"Name,omitempty"`
	Disabled string `json:"Disabled,omitempty"`
	Privileged int64 `json:"Privileged,omitempty"`
	Memberships []GroupReference `json:"Memberships,omitempty"`
	Hyperlinks []UserIdNameGet200ResponseAllOfHyperlinksInner `json:"_hyperlinks,omitempty"`
}
