// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomfieldIdPutRequest - CustomfieldIdPutRequest struct
type CustomfieldIdPutRequest struct {
	Name string `json:"Name,omitempty"`
	Type string `json:"Type,omitempty"`
	RenderType string `json:"RenderType,omitempty"`
	LookupType string `json:"LookupType,omitempty"`
	ValidationHint string `json:"ValidationHint,omitempty"`
	Description string `json:"Description,omitempty"`
	EntryHint string `json:"EntryHint,omitempty"`
	MaxValues string `json:"MaxValues,omitempty"`
	UniqueValues *PerlBoolean `json:"UniqueValues,omitempty"`
	Pattern string `json:"Pattern,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
}
