// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UserIdOrNameIdOrNameParameter - UserIdOrNameIdOrNameParameter struct
type UserIdOrNameIdOrNameParameter struct {
}
