// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RtGet200Response - RtGet200Response struct
type RtGet200Response struct {
	Version string `json:"Version,omitempty"`
	Plugins []string `json:"Plugins,omitempty"`
}
