// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ArticleIdGet200ResponseAllOfParent - ArticleIdGet200ResponseAllOfParent struct
type ArticleIdGet200ResponseAllOfParent struct {
}
