// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HyperlinkMemberships - Show groups whose member this user/group is.
type HyperlinkMemberships struct {
}
