// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomRolePropertiesCommon - Properties of a custom role, which is a ticket role beyond Owner, Requestor, Cc and AdminCc.
type CustomRolePropertiesCommon struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	MaxValues string `json:"MaxValues,omitempty"`
	EntryHint string `json:"EntryHint,omitempty"`
	LookupType string `json:"LookupType,omitempty"`
	Disabled string `json:"Disabled,omitempty"`
}
