// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomfieldIdAppliestoPost201Response - CustomfieldIdAppliestoPost201Response struct
type CustomfieldIdAppliestoPost201Response struct {
	Message string `json:"message,omitempty"`
	ObjectId int32 `json:"ObjectId,omitempty"`
	ObjectType string `json:"ObjectType,omitempty"`
	ObjectName string `json:"ObjectName,omitempty"`
}
