// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HyperlinkTicketLink - A link to another ticket
type HyperlinkTicketLink struct {
	Id RTID `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
