// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CatalogPropertiesCommon - Properties of a catalog, which is to assets what a queue is to tickets.
type CatalogPropertiesCommon struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Lifecycle string `json:"Lifecycle,omitempty"`
	Disabled string `json:"Disabled,omitempty"`
}
