// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QueueIdOrNameIdOrNameParameter - QueueIdOrNameIdOrNameParameter struct
type QueueIdOrNameIdOrNameParameter struct {
}
