// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// PerlBooleanInteger - Same as perlBoolean but in the slightly more sensible integer format.
type PerlBooleanInteger struct {
}
