// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// UserNameGroupsPut200ResponseInner - Alternating between perlbooleanInteger and a string message, starting witht a perlbooleanInteger. The boolean will tell whether the addiotion to a particular group was a success.
type UserNameGroupsPut200ResponseInner struct {
}
