// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QueueReference - A reference to a queue.
type QueueReference struct {
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
