// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// TicketLinksUpload - Ticket links when creating or updating a ticket.
type TicketLinksUpload struct {
	DependsOn interface{} `json:"DependsOn,omitempty"`
	Child interface{} `json:"Child,omitempty"`
	ReferredToBy interface{} `json:"ReferredToBy,omitempty"`
	Parent interface{} `json:"Parent,omitempty"`
	DependedOnBy interface{} `json:"DependedOnBy,omitempty"`
	RefersTo interface{} `json:"RefersTo,omitempty"`
}
