// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CatalogIdOrNameIdOrNameParameter - CatalogIdOrNameIdOrNameParameter struct
type CatalogIdOrNameIdOrNameParameter struct {
}
