// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CatalogIdNameGet200Response - CatalogIdNameGet200Response struct
type CatalogIdNameGet200Response struct {
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	CustomFields []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Lifecycle string `json:"Lifecycle,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
}
