// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// ClassPropertiesCommon - Properties of an article class.
type ClassPropertiesCommon struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Disabled string `json:"Disabled,omitempty"`
}
