// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LifecycleDocument - A lifecycle as RT hands it back -- its whole configuration, plus the name it is addressed by. A lifecycle has no id at all, and the `type` here is the kind of object it governs rather than the kind of thing it is.
type LifecycleDocument struct {
	Type string `json:"type,omitempty"`
	Initial []string `json:"initial,omitempty"`
	Active []string `json:"active,omitempty"`
	Inactive []string `json:"inactive,omitempty"`
	Defaults map[string]string `json:"defaults,omitempty"`
	Transitions map[string][]string `json:"transitions,omitempty"`
	Rights map[string]string `json:"rights,omitempty"`
	Actions []LifecycleConfigurationActionsInner `json:"actions,omitempty"`
	Colors map[string]string `json:"colors,omitempty"`
	Name string `json:"name,omitempty"`
	CanonicalCase map[string]string `json:"canonical_case,omitempty"`
	Url string `json:"_url,omitempty"`
}
