// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldCommon - Fields shared by operations targeted at the customfields themselves
type CustomFieldCommon struct {
	Name string `json:"Name,omitempty"`
	Type string `json:"Type,omitempty"`
	RenderType string `json:"RenderType,omitempty"`
	LookupType string `json:"LookupType,omitempty"`
	ValidationHint string `json:"ValidationHint,omitempty"`
}
