// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// RightsBulkOutcome - What became of one grant or revoke in a bulk request.
type RightsBulkOutcome struct {
	Right string `json:"Right,omitempty"`
	Status int32 `json:"status,omitempty"`
	Group *PrincipalReference `json:"Group,omitempty"`
	User *PrincipalReference `json:"User,omitempty"`
}
