// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// HyperlinkCustomFieldValues - Reference to available customfield values of select type CFs.
type HyperlinkCustomFieldValues struct {
}
