// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// Hyperlink - Parent object for _hyperlink objects
type Hyperlink struct {
	Ref string `json:"ref,omitempty"`
	Url string `json:"_url,omitempty"`
}
