// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// QueueIdNameGet200Response - QueueIdNameGet200Response struct
type QueueIdNameGet200Response struct {
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	CustomFields []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
	SLADisabled *PerlBoolean `json:"SLADisabled,omitempty"`
	Cc []UserReference `json:"Cc,omitempty"`
	AdminCc []UserReference `json:"AdminCc,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	TicketCustomFields []CustomFieldsAppliedInner `json:"TicketCustomFields,omitempty"`
	CommentAddress string `json:"CommentAddress,omitempty"`
	Disabled *PerlBoolean `json:"Disabled,omitempty"`
	Lifecycle string `json:"Lifecycle,omitempty"`
	Hyperlinks []QueueIdNameGet200ResponseAllOfHyperlinksInner `json:"_hyperlinks,omitempty"`
	CorrespondAddress string `json:"CorrespondAddress,omitempty"`
	TicketTransactionCustomFields []interface{} `json:"TicketTransactionCustomFields,omitempty"`
	SubjectTag string `json:"SubjectTag,omitempty"`
}
