// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// LifecycleReference - A reference to a lifecycle. Lifecycles are addressed by name.
type LifecycleReference struct {
	Url string `json:"_url,omitempty"`
	Id RTID `json:"id,omitempty"`
	Type string `json:"type,omitempty"`
}
