// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomFieldsArrayInner - CustomFieldsArrayInner struct
type CustomFieldsArrayInner struct {
	Id RTID `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Values []interface{} `json:"values,omitempty"`
	Url string `json:"_url,omitempty"`
	Type string `json:"type,omitempty"`
}
