// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// CustomfieldIdValuePostRequest - CustomfieldIdValuePostRequest struct
type CustomfieldIdValuePostRequest struct {
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	SortOrder string `json:"SortOrder,omitempty"`
	Category string `json:"Category,omitempty"`
}
