// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// GroupIdGet200Response - GroupIdGet200Response struct
type GroupIdGet200Response struct {
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	CustomFields []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Hyperlinks []GroupIdGet200ResponseAllOfHyperlinksInner `json:"_hyperlinks,omitempty"`
	Domain string `json:"Domain,omitempty"`
	Instance string `json:"Instance,omitempty"`
	Disabled string `json:"Disabled,omitempty"`
	Members []GroupIdGet200ResponseAllOfMembersInner `json:"Members,omitempty"`
}
