// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

// AssetIdGet200Response - AssetIdGet200Response struct
type AssetIdGet200Response struct {
	Id RTID `json:"id,omitempty"`
	Created string `json:"Created,omitempty"`
	Creator *UserReference `json:"Creator,omitempty"`
	LastUpdated string `json:"LastUpdated,omitempty"`
	LastUpdatedBy *UserReference `json:"LastUpdatedBy,omitempty"`
	CustomFields []CustomFieldsArrayInner `json:"CustomFields,omitempty"`
	Name string `json:"Name,omitempty"`
	Description string `json:"Description,omitempty"`
	Catalog *CatalogReference `json:"Catalog,omitempty"`
	Status string `json:"Status,omitempty"`
	Owner *UserReference `json:"Owner,omitempty"`
	HeldBy []UserReference `json:"HeldBy,omitempty"`
	Contact []UserReference `json:"Contact,omitempty"`
}
