// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// ArticleModel is the Terraform model for article.
type ArticleModel struct {
	Id types.String `tfsdk:"id"`
	Created types.String `tfsdk:"created"`
	Creator jsontypes.Normalized `tfsdk:"creator"`
	LastUpdated types.String `tfsdk:"last_updated"`
	LastUpdatedBy jsontypes.Normalized `tfsdk:"last_updated_by"`
	CustomFields jsontypes.Normalized `tfsdk:"custom_fields"`
	Name types.String `tfsdk:"name"`
	Summary types.String `tfsdk:"summary"`
	SortOrder types.String `tfsdk:"sort_order"`
	Class jsontypes.Normalized `tfsdk:"class"`
	Parent jsontypes.Normalized `tfsdk:"parent"`
	URI types.String `tfsdk:"uri"`
	Disabled types.String `tfsdk:"disabled"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ArticleModel) ToClientModel() (*client.ArticlePostRequest, error) {
	out := &client.ArticlePostRequest{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.CustomFields.IsNull() && !m.CustomFields.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomFields.ValueString()), &out.CustomFields); err != nil {
			return out, fmt.Errorf("custom_fields: %w", err)
		}
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Summary.IsNull() && !m.Summary.IsUnknown() {
		out.Summary = m.Summary.ValueString()
	}
	if !m.SortOrder.IsNull() && !m.SortOrder.IsUnknown() {
		out.SortOrder = m.SortOrder.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Class.IsNull() && !m.Class.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Class.ValueString()), &out.Class); err != nil {
			return out, fmt.Errorf("class: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Parent.IsNull() && !m.Parent.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Parent.ValueString()), &out.Parent); err != nil {
			return out, fmt.Errorf("parent: %w", err)
		}
	}
	if !m.URI.IsNull() && !m.URI.IsUnknown() {
		out.URI = m.URI.ValueString()
	}
	if !m.Disabled.IsNull() && !m.Disabled.IsUnknown() {
		out.Disabled = m.Disabled.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *ArticleModel) ToUpdateModel() (*client.ArticleIdPutRequest, error) {
	out := &client.ArticleIdPutRequest{}
	if !m.CustomFields.IsNull() && !m.CustomFields.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomFields.ValueString()), &out.CustomFields); err != nil {
			return out, fmt.Errorf("custom_fields: %w", err)
		}
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Summary.IsNull() && !m.Summary.IsUnknown() {
		out.Summary = m.Summary.ValueString()
	}
	if !m.SortOrder.IsNull() && !m.SortOrder.IsUnknown() {
		out.SortOrder = m.SortOrder.ValueString()
	}
	if !m.Class.IsNull() && !m.Class.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Class.ValueString()), &out.Class); err != nil {
			return out, fmt.Errorf("class: %w", err)
		}
	}
	if !m.Parent.IsNull() && !m.Parent.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Parent.ValueString()), &out.Parent); err != nil {
			return out, fmt.Errorf("parent: %w", err)
		}
	}
	if !m.URI.IsNull() && !m.URI.IsUnknown() {
		out.URI = m.URI.ValueString()
	}
	if !m.Disabled.IsNull() && !m.Disabled.IsUnknown() {
		out.Disabled = m.Disabled.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *ArticleModel) FromClientModel(c *client.ArticleIdGet200Response) {
	m.Id = types.StringValue(string(c.Id))
	m.Created = types.StringValue(c.Created)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Creator); err == nil {
		if m.Creator.IsNull() || m.Creator.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Creator.ValueString()) {
			m.Creator = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.LastUpdated = types.StringValue(c.LastUpdated)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LastUpdatedBy); err == nil {
		if m.LastUpdatedBy.IsNull() || m.LastUpdatedBy.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LastUpdatedBy.ValueString()) {
			m.LastUpdatedBy = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.CustomFields.IsUnknown() {
		m.CustomFields = jsontypes.NewNormalizedNull()
	}
	m.Name = types.StringValue(c.Name)
	m.Summary = types.StringValue(c.Summary)
	m.SortOrder = types.StringValue(c.SortOrder)
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Parent.IsUnknown() {
		m.Parent = jsontypes.NewNormalizedNull()
	}
	m.URI = types.StringValue(c.URI)
	m.Disabled = types.StringValue(c.Disabled)
}
