// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// AssetModel is the Terraform model for asset.
type AssetModel struct {
	Id types.String `tfsdk:"id"`
	Created types.String `tfsdk:"created"`
	Creator jsontypes.Normalized `tfsdk:"creator"`
	LastUpdated types.String `tfsdk:"last_updated"`
	LastUpdatedBy jsontypes.Normalized `tfsdk:"last_updated_by"`
	CustomFields jsontypes.Normalized `tfsdk:"custom_fields"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	Catalog jsontypes.Normalized `tfsdk:"catalog"`
	Status types.String `tfsdk:"status"`
	Owner jsontypes.Normalized `tfsdk:"owner"`
	HeldBy jsontypes.Normalized `tfsdk:"held_by"`
	Contact jsontypes.Normalized `tfsdk:"contact"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *AssetModel) ToClientModel() (*client.AssetPostRequest, error) {
	out := &client.AssetPostRequest{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.CustomFields.IsNull() && !m.CustomFields.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomFields.ValueString()), &out.CustomFields); err != nil {
			return out, fmt.Errorf("custom_fields: %w", err)
		}
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Catalog.IsNull() && !m.Catalog.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Catalog.ValueString()), &out.Catalog); err != nil {
			return out, fmt.Errorf("catalog: %w", err)
		}
	}
	if !m.Status.IsNull() && !m.Status.IsUnknown() {
		out.Status = m.Status.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Owner.IsNull() && !m.Owner.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Owner.ValueString()), &out.Owner); err != nil {
			return out, fmt.Errorf("owner: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.HeldBy.IsNull() && !m.HeldBy.IsUnknown() {
		if err := json.Unmarshal([]byte(m.HeldBy.ValueString()), &out.HeldBy); err != nil {
			return out, fmt.Errorf("held_by: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Contact.IsNull() && !m.Contact.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Contact.ValueString()), &out.Contact); err != nil {
			return out, fmt.Errorf("contact: %w", err)
		}
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *AssetModel) ToUpdateModel() (*client.AssetIdPutRequest, error) {
	out := &client.AssetIdPutRequest{}
	if !m.CustomFields.IsNull() && !m.CustomFields.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomFields.ValueString()), &out.CustomFields); err != nil {
			return out, fmt.Errorf("custom_fields: %w", err)
		}
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.Catalog.IsNull() && !m.Catalog.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Catalog.ValueString()), &out.Catalog); err != nil {
			return out, fmt.Errorf("catalog: %w", err)
		}
	}
	if !m.Status.IsNull() && !m.Status.IsUnknown() {
		out.Status = m.Status.ValueString()
	}
	if !m.Owner.IsNull() && !m.Owner.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Owner.ValueString()), &out.Owner); err != nil {
			return out, fmt.Errorf("owner: %w", err)
		}
	}
	if !m.HeldBy.IsNull() && !m.HeldBy.IsUnknown() {
		if err := json.Unmarshal([]byte(m.HeldBy.ValueString()), &out.HeldBy); err != nil {
			return out, fmt.Errorf("held_by: %w", err)
		}
	}
	if !m.Contact.IsNull() && !m.Contact.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Contact.ValueString()), &out.Contact); err != nil {
			return out, fmt.Errorf("contact: %w", err)
		}
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *AssetModel) FromClientModel(c *client.AssetIdGet200Response) {
	m.Id = types.StringValue(string(c.Id))
	m.Created = types.StringValue(c.Created)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Creator); err == nil {
		if m.Creator.IsNull() || m.Creator.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Creator.ValueString()) {
			m.Creator = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.LastUpdated = types.StringValue(c.LastUpdated)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LastUpdatedBy); err == nil {
		if m.LastUpdatedBy.IsNull() || m.LastUpdatedBy.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LastUpdatedBy.ValueString()) {
			m.LastUpdatedBy = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.CustomFields.IsUnknown() {
		m.CustomFields = jsontypes.NewNormalizedNull()
	}
	m.Name = types.StringValue(c.Name)
	m.Description = types.StringValue(c.Description)
	m.Status = types.StringValue(c.Status)
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Owner.IsUnknown() {
		m.Owner = jsontypes.NewNormalizedNull()
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.HeldBy.IsUnknown() {
		m.HeldBy = jsontypes.NewNormalizedNull()
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Contact.IsUnknown() {
		m.Contact = jsontypes.NewNormalizedNull()
	}
}
