// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// ClassRightModel is the Terraform model for class_right.
type ClassRightModel struct {
	Right types.String `tfsdk:"right"`
	Group jsontypes.Normalized `tfsdk:"group"`
	User jsontypes.Normalized `tfsdk:"user"`
	IdOrName types.String `tfsdk:"id_or_name"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *ClassRightModel) ToClientModel() (*client.RightGrant, error) {
	out := &client.RightGrant{}
	if !m.Right.IsNull() && !m.Right.IsUnknown() {
		out.Right = m.Right.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Group.IsNull() && !m.Group.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Group.ValueString()), &out.Group); err != nil {
			return out, fmt.Errorf("group: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.User.IsNull() && !m.User.IsUnknown() {
		if err := json.Unmarshal([]byte(m.User.ValueString()), &out.User); err != nil {
			return out, fmt.Errorf("user: %w", err)
		}
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *ClassRightModel) FromClientModel(c *client.QueueIdNameRightsPost201Response) {
	m.Right = types.StringValue(c.Right)
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Group.IsUnknown() {
		m.Group = jsontypes.NewNormalizedNull()
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.User.IsUnknown() {
		m.User = jsontypes.NewNormalizedNull()
	}
}
