// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// CustomfieldValueModel is the Terraform model for customfield_value.
type CustomfieldValueModel struct {
	Id types.String `tfsdk:"id"`
	Created types.String `tfsdk:"created"`
	Creator jsontypes.Normalized `tfsdk:"creator"`
	LastUpdated types.String `tfsdk:"last_updated"`
	LastUpdatedBy jsontypes.Normalized `tfsdk:"last_updated_by"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	SortOrder types.String `tfsdk:"sort_order"`
	Category types.String `tfsdk:"category"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *CustomfieldValueModel) ToClientModel() (*client.CustomfieldIdValuePostRequest, error) {
	out := &client.CustomfieldIdValuePostRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.SortOrder.IsNull() && !m.SortOrder.IsUnknown() {
		out.SortOrder = m.SortOrder.ValueString()
	}
	if !m.Category.IsNull() && !m.Category.IsUnknown() {
		out.Category = m.Category.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *CustomfieldValueModel) ToUpdateModel() (*client.CustomFieldValuePropertiesCommon, error) {
	out := &client.CustomFieldValuePropertiesCommon{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.SortOrder.IsNull() && !m.SortOrder.IsUnknown() {
		out.SortOrder = m.SortOrder.ValueString()
	}
	if !m.Category.IsNull() && !m.Category.IsUnknown() {
		out.Category = m.Category.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *CustomfieldValueModel) FromClientModel(c *client.CustomfieldIdValueIdGet200Response) {
	m.Id = types.StringValue(string(c.Id))
	m.Created = types.StringValue(c.Created)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Creator); err == nil {
		if m.Creator.IsNull() || m.Creator.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Creator.ValueString()) {
			m.Creator = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.LastUpdated = types.StringValue(c.LastUpdated)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LastUpdatedBy); err == nil {
		if m.LastUpdatedBy.IsNull() || m.LastUpdatedBy.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LastUpdatedBy.ValueString()) {
			m.LastUpdatedBy = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Name = types.StringValue(c.Name)
	m.Description = types.StringValue(c.Description)
	m.SortOrder = types.StringValue(c.SortOrder)
	m.Category = types.StringValue(c.Category)
}
