// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ resource.Resource = &CustomfieldAppliestoResource{}
var _ resource.ResourceWithImportState = &CustomfieldAppliestoResource{}

func NewCustomfieldAppliestoResource() resource.Resource {
	return &CustomfieldAppliestoResource{}
}

type CustomfieldAppliestoResource struct {
	client *client.Client
}

func (r *CustomfieldAppliestoResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_customfield_appliesto"
}

func (r *CustomfieldAppliestoResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a customfield_appliesto resource.",
		Attributes: map[string]schema.Attribute{
			"message": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"object_id": schema.Int64Attribute{
				Required:    true,
				Description: "",
			},
			"object_type": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"object_name": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Identifier of the id.",
			},
		},
	}
}

func (r *CustomfieldAppliestoResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *CustomfieldAppliestoResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan CustomfieldAppliestoModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid customfield_appliesto configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", fmt.Sprintf("/customfield/%v/appliesto", plan.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating customfield_appliesto", err.Error())
		return
	}

	// A create that answers 201 with nothing but a Location header -- RT does
	// this for tenants and applications. The identifier is in that header, and
	// everything else the server assigned has to be fetched.
	if len(respBody) == 0 {
		plan.Id = types.StringValue(client.IDFromLocation(location))
	}

	if len(respBody) > 0 {
		var result client.CustomfieldIdAppliestoPost201Response
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created customfield_appliesto resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *CustomfieldAppliestoResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// No read endpoint available; keep existing state as-is.
}

func (r *CustomfieldAppliestoResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No update endpoint: nothing here can change on the server, so the plan
	// stands. But EVERY Computed attribute is unknown in a plan, and a provider
	// must answer known values after an apply -- persisting the plan as it
	// stands earns "Provider returned invalid result object after apply". The
	// known values come from a read.
	var plan CustomfieldAppliestoModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *CustomfieldAppliestoResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *CustomfieldAppliestoResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
