// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ datasource.DataSource = &CustomfieldDataSource{}

func NewCustomfieldDataSource() datasource.DataSource {
	return &CustomfieldDataSource{}
}

type CustomfieldDataSource struct {
	client *client.Client
}

func (d *CustomfieldDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_customfield"
}

func (d *CustomfieldDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a customfield data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Integer identifier",
			},
			"created": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"creator": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"last_updated": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"last_updated_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"type": schema.StringAttribute{
				Required:    true,
				Description: "Custom field type.",
			},
			"render_type": schema.StringAttribute{
				Computed:    true,
				Description: "How the custom field is displayed in the UI.",
			},
			"lookup_type": schema.StringAttribute{
				Required:    true,
				Description: "What type of object this custom field applies to?",
			},
			"validation_hint": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"entry_hint": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"unique_values": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"pattern": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"sort_order": schema.StringAttribute{
				Computed:    true,
				Description: "Seems to be an enumeration of some kind.",
			},
			"disabled": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"values": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"_hyperlinks": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Things and operations related to this ticket. Probably contains multiple lifecycle operations.",
			},
			"max_values": schema.StringAttribute{
				Required:    true,
				Description: "Whether the field is single valued",
			},
		},
	}
}

func (d *CustomfieldDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *CustomfieldDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config CustomfieldModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/customfield/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading customfield", err.Error())
		return
	}

	var result client.CustomfieldIdGet200Response
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read customfield data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
