// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ datasource.DataSource = &CustomfieldAppliestoDataSource{}

func NewCustomfieldAppliestoDataSource() datasource.DataSource {
	return &CustomfieldAppliestoDataSource{}
}

type CustomfieldAppliestoDataSource struct {
	client *client.Client
}

func (d *CustomfieldAppliestoDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_customfield_appliesto"
}

func (d *CustomfieldAppliestoDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a customfield_appliesto data source.",
		Attributes: map[string]schema.Attribute{
			"message": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"object_id": schema.Int64Attribute{
				Required:    true,
				Description: "",
			},
			"object_type": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"object_name": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Identifier of the id.",
			},
		},
	}
}

func (d *CustomfieldAppliestoDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *CustomfieldAppliestoDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	resp.Diagnostics.AddError("Not Supported", "Read is not supported for customfield_appliesto")
}
