// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ datasource.DataSource = &CustomfieldValueDataSource{}

func NewCustomfieldValueDataSource() datasource.DataSource {
	return &CustomfieldValueDataSource{}
}

type CustomfieldValueDataSource struct {
	client *client.Client
}

func (d *CustomfieldValueDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_customfield_value"
}

func (d *CustomfieldValueDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a customfield_value data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Integer identifier",
			},
			"created": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"creator": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"last_updated": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"last_updated_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"sort_order": schema.StringAttribute{
				Computed:    true,
				Description: "Seems to be an enumeration of some kind.",
			},
			"category": schema.StringAttribute{
				Computed:    true,
				Description: "Groups values under a heading, for a field based on another.",
			},
		},
	}
}

func (d *CustomfieldValueDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *CustomfieldValueDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config CustomfieldValueModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/customfield/%v/value/%v", config.Id.ValueString(), config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading customfield_value", err.Error())
		return
	}

	var result client.CustomfieldIdValueIdGet200Response
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read customfield_value data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
