// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// CustomfieldAppliestoModel is the Terraform model for customfield_appliesto.
type CustomfieldAppliestoModel struct {
	Message types.String `tfsdk:"message"`
	ObjectId types.Int64 `tfsdk:"object_id"`
	ObjectType types.String `tfsdk:"object_type"`
	ObjectName types.String `tfsdk:"object_name"`
	Id types.String `tfsdk:"id"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *CustomfieldAppliestoModel) ToClientModel() (*client.CustomfieldIdAppliestoPostRequest, error) {
	out := &client.CustomfieldIdAppliestoPostRequest{}
	if !m.ObjectId.IsNull() && !m.ObjectId.IsUnknown() {
		out.ObjectId = int32(m.ObjectId.ValueInt64())
	}
	return out, nil
}


// FromClientModel updates the Terraform model from a client model.
func (m *CustomfieldAppliestoModel) FromClientModel(c *client.CustomfieldIdAppliestoPost201Response) {
	m.Message = types.StringValue(c.Message)
	m.ObjectId = types.Int64Value(int64(c.ObjectId))
	m.ObjectType = types.StringValue(c.ObjectType)
	m.ObjectName = types.StringValue(c.ObjectName)
}
