// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// CustomfieldModel is the Terraform model for customfield.
type CustomfieldModel struct {
	Id types.String `tfsdk:"id"`
	Created types.String `tfsdk:"created"`
	Creator jsontypes.Normalized `tfsdk:"creator"`
	LastUpdated types.String `tfsdk:"last_updated"`
	LastUpdatedBy jsontypes.Normalized `tfsdk:"last_updated_by"`
	Name types.String `tfsdk:"name"`
	Type types.String `tfsdk:"type"`
	RenderType types.String `tfsdk:"render_type"`
	LookupType types.String `tfsdk:"lookup_type"`
	ValidationHint types.String `tfsdk:"validation_hint"`
	Description types.String `tfsdk:"description"`
	EntryHint types.String `tfsdk:"entry_hint"`
	UniqueValues types.String `tfsdk:"unique_values"`
	Pattern types.String `tfsdk:"pattern"`
	SortOrder types.String `tfsdk:"sort_order"`
	Disabled types.String `tfsdk:"disabled"`
	Values jsontypes.Normalized `tfsdk:"values"`
	Hyperlinks jsontypes.Normalized `tfsdk:"_hyperlinks"`
	MaxValues types.String `tfsdk:"max_values"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *CustomfieldModel) ToClientModel() (*client.CustomfieldPostRequest, error) {
	out := &client.CustomfieldPostRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	if !m.RenderType.IsNull() && !m.RenderType.IsUnknown() {
		out.RenderType = m.RenderType.ValueString()
	}
	if !m.LookupType.IsNull() && !m.LookupType.IsUnknown() {
		out.LookupType = m.LookupType.ValueString()
	}
	if !m.ValidationHint.IsNull() && !m.ValidationHint.IsUnknown() {
		out.ValidationHint = m.ValidationHint.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.EntryHint.IsNull() && !m.EntryHint.IsUnknown() {
		out.EntryHint = m.EntryHint.ValueString()
	}
	if !m.Pattern.IsNull() && !m.Pattern.IsUnknown() {
		out.Pattern = m.Pattern.ValueString()
	}
	if !m.SortOrder.IsNull() && !m.SortOrder.IsUnknown() {
		out.SortOrder = m.SortOrder.ValueString()
	}
	if !m.MaxValues.IsNull() && !m.MaxValues.IsUnknown() {
		out.MaxValues = m.MaxValues.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *CustomfieldModel) ToUpdateModel() (*client.CustomfieldIdPutRequest, error) {
	out := &client.CustomfieldIdPutRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	if !m.RenderType.IsNull() && !m.RenderType.IsUnknown() {
		out.RenderType = m.RenderType.ValueString()
	}
	if !m.LookupType.IsNull() && !m.LookupType.IsUnknown() {
		out.LookupType = m.LookupType.ValueString()
	}
	if !m.ValidationHint.IsNull() && !m.ValidationHint.IsUnknown() {
		out.ValidationHint = m.ValidationHint.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.EntryHint.IsNull() && !m.EntryHint.IsUnknown() {
		out.EntryHint = m.EntryHint.ValueString()
	}
	if !m.Pattern.IsNull() && !m.Pattern.IsUnknown() {
		out.Pattern = m.Pattern.ValueString()
	}
	if !m.SortOrder.IsNull() && !m.SortOrder.IsUnknown() {
		out.SortOrder = m.SortOrder.ValueString()
	}
	if !m.MaxValues.IsNull() && !m.MaxValues.IsUnknown() {
		out.MaxValues = m.MaxValues.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *CustomfieldModel) FromClientModel(c *client.CustomfieldIdGet200Response) {
	m.Id = types.StringValue(string(c.Id))
	m.Created = types.StringValue(c.Created)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Creator); err == nil {
		if m.Creator.IsNull() || m.Creator.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Creator.ValueString()) {
			m.Creator = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.LastUpdated = types.StringValue(c.LastUpdated)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LastUpdatedBy); err == nil {
		if m.LastUpdatedBy.IsNull() || m.LastUpdatedBy.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LastUpdatedBy.ValueString()) {
			m.LastUpdatedBy = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Name = types.StringValue(c.Name)
	m.Type = types.StringValue(c.Type)
	m.RenderType = types.StringValue(c.RenderType)
	m.LookupType = types.StringValue(c.LookupType)
	m.ValidationHint = types.StringValue(c.ValidationHint)
	m.Description = types.StringValue(c.Description)
	m.EntryHint = types.StringValue(c.EntryHint)
	m.Pattern = types.StringValue(c.Pattern)
	m.SortOrder = types.StringValue(c.SortOrder)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Values); err == nil {
		if m.Values.IsNull() || m.Values.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Values.ValueString()) {
			m.Values = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Hyperlinks); err == nil {
		if m.Hyperlinks.IsNull() || m.Hyperlinks.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Hyperlinks.ValueString()) {
			m.Hyperlinks = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.MaxValues = types.StringValue(c.MaxValues)
}
