// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ resource.Resource = &GlobalRightResource{}
var _ resource.ResourceWithImportState = &GlobalRightResource{}

func NewGlobalRightResource() resource.Resource {
	return &GlobalRightResource{}
}

type GlobalRightResource struct {
	client *client.Client
}

func (r *GlobalRightResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_global_right"
}

func (r *GlobalRightResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a global_right resource.",
		Attributes: map[string]schema.Attribute{
			"right": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"group": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"user": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
		},
	}
}

func (r *GlobalRightResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *GlobalRightResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan GlobalRightModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid global_right configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/global/rights", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating global_right", err.Error())
		return
	}

	// Nothing to read back with: the create's own answer is all there is.
	_ = location

	if len(respBody) > 0 {
		var result client.QueueIdNameRightsPost201Response
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created global_right resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *GlobalRightResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	// No read endpoint available; keep existing state as-is.
}

func (r *GlobalRightResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	// No update endpoint: nothing here can change on the server, so the plan
	// stands. But EVERY Computed attribute is unknown in a plan, and a provider
	// must answer known values after an apply -- persisting the plan as it
	// stands earns "Provider returned invalid result object after apply". The
	// known values come from a read.
	var plan GlobalRightModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *GlobalRightResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	// No delete endpoint available; remove the resource from state.
}

func (r *GlobalRightResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
