// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// GroupMemberModel is the Terraform model for group_member.
type GroupMemberModel struct {
	Id types.String `tfsdk:"id"`
}



