// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// GroupModel is the Terraform model for group.
type GroupModel struct {
	Id types.String `tfsdk:"id"`
	Created types.String `tfsdk:"created"`
	Creator jsontypes.Normalized `tfsdk:"creator"`
	LastUpdated types.String `tfsdk:"last_updated"`
	LastUpdatedBy jsontypes.Normalized `tfsdk:"last_updated_by"`
	CustomFields jsontypes.Normalized `tfsdk:"custom_fields"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	Hyperlinks jsontypes.Normalized `tfsdk:"hyperlinks"`
	Domain types.String `tfsdk:"domain"`
	Instance types.String `tfsdk:"instance"`
	Disabled types.String `tfsdk:"disabled"`
	Members jsontypes.Normalized `tfsdk:"members"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *GroupModel) ToClientModel() (*client.GroupPostRequest, error) {
	out := &client.GroupPostRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.Disabled.IsNull() && !m.Disabled.IsUnknown() {
		out.Disabled = m.Disabled.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *GroupModel) ToUpdateModel() (*client.GroupIdPutRequest, error) {
	out := &client.GroupIdPutRequest{}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.Disabled.IsNull() && !m.Disabled.IsUnknown() {
		out.Disabled = m.Disabled.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *GroupModel) FromClientModel(c *client.GroupIdGet200Response) {
	m.Id = types.StringValue(string(c.Id))
	m.Created = types.StringValue(c.Created)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Creator); err == nil {
		if m.Creator.IsNull() || m.Creator.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Creator.ValueString()) {
			m.Creator = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.LastUpdated = types.StringValue(c.LastUpdated)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LastUpdatedBy); err == nil {
		if m.LastUpdatedBy.IsNull() || m.LastUpdatedBy.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LastUpdatedBy.ValueString()) {
			m.LastUpdatedBy = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.CustomFields); err == nil {
		if m.CustomFields.IsNull() || m.CustomFields.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.CustomFields.ValueString()) {
			m.CustomFields = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Name = types.StringValue(c.Name)
	m.Description = types.StringValue(c.Description)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Hyperlinks); err == nil {
		if m.Hyperlinks.IsNull() || m.Hyperlinks.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Hyperlinks.ValueString()) {
			m.Hyperlinks = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Domain = types.StringValue(c.Domain)
	m.Instance = types.StringValue(c.Instance)
	m.Disabled = types.StringValue(c.Disabled)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Members); err == nil {
		if m.Members.IsNull() || m.Members.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Members.ValueString()) {
			m.Members = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
