// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// LifecycleMapModel is the Terraform model for lifecycle_map.
type LifecycleMapModel struct {
	Name types.String `tfsdk:"name"`
}



