// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ datasource.DataSource = &LifecycleDataSource{}

func NewLifecycleDataSource() datasource.DataSource {
	return &LifecycleDataSource{}
}

type LifecycleDataSource struct {
	client *client.Client
}

func (d *LifecycleDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_lifecycle"
}

func (d *LifecycleDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a lifecycle data source.",
		Attributes: map[string]schema.Attribute{
			"type": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"initial": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Statuses a new object may start in.",
			},
			"active": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Statuses meaning work is ongoing.",
			},
			"inactive": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Statuses meaning work has stopped.",
			},
			"defaults": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Which status an action moves an object to.",
			},
			"transitions": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Which statuses each status may move to. The empty key is the transition into the lifecycle.",
			},
			"rights": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "The right required to make a transition.",
			},
			"actions": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "The transitions offered in the UI, as alternating \"from -> to\" strings and their configuration.",
			},
			"colors": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "A colour per status, as shown in the UI.",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"canonical_case": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "The capitalisation RT treats as canonical for each status, keyed by the lower-case form.",
			},
			"url": schema.StringAttribute{
				Computed:    true,
				Description: "An URL pointing somewhere in the web",
			},
		},
	}
}

func (d *LifecycleDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *LifecycleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config LifecycleModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/lifecycle/%v", config.Name.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading lifecycle", err.Error())
		return
	}

	var result client.LifecycleDocument
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read lifecycle data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
