// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ resource.Resource = &LifecycleResource{}
var _ resource.ResourceWithImportState = &LifecycleResource{}

func NewLifecycleResource() resource.Resource {
	return &LifecycleResource{}
}

type LifecycleResource struct {
	client *client.Client
}

func (r *LifecycleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_lifecycle"
}

func (r *LifecycleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a lifecycle resource.",
		Attributes: map[string]schema.Attribute{
			"type": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"initial": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Statuses a new object may start in.",
			},
			"active": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Statuses meaning work is ongoing.",
			},
			"inactive": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Statuses meaning work has stopped.",
			},
			"defaults": schema.StringAttribute{
				Computed:    true,
				Description: "Which status an action moves an object to.",
			},
			"transitions": schema.StringAttribute{
				Computed:    true,
				Description: "Which statuses each status may move to. The empty key is the transition into the lifecycle.",
			},
			"rights": schema.StringAttribute{
				Computed:    true,
				Description: "The right required to make a transition.",
			},
			"actions": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "The transitions offered in the UI, as alternating \"from -> to\" strings and their configuration.",
			},
			"colors": schema.StringAttribute{
				Computed:    true,
				Description: "A colour per status, as shown in the UI.",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"canonical_case": schema.StringAttribute{
				Computed:    true,
				Description: "The capitalisation RT treats as canonical for each status, keyed by the lower-case form.",
			},
			"_url": schema.StringAttribute{
				Computed:    true,
				Description: "An URL pointing somewhere in the web",
			},
		},
	}
}

func (r *LifecycleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *LifecycleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan LifecycleModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid lifecycle configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/lifecycles", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating lifecycle", err.Error())
		return
	}

	// A create that answers 201 with nothing but a Location header -- RT does
	// this for tenants and applications. The identifier is in that header, and
	// everything else the server assigned has to be fetched.
	if len(respBody) == 0 {
		plan.Name = types.StringValue(client.IDFromLocation(location))

		respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/lifecycle/%v", plan.Name.ValueString()), nil)
		if err != nil {
			resp.Diagnostics.AddError("Error reading back the created lifecycle", err.Error())
			return
		}
	}

	if len(respBody) > 0 {
		var result client.LifecycleDocument
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created lifecycle resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *LifecycleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state LifecycleModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Name.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/lifecycle/%v", state.Name.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading lifecycle", err.Error())
		return
	}

	var result client.LifecycleDocument
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *LifecycleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan LifecycleModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state LifecycleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The UPDATE model, not the create one -- see ToUpdateModel.
	reqBody, err := plan.ToUpdateModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid lifecycle configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PUT", fmt.Sprintf("/lifecycle/%v", state.Name.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating lifecycle", err.Error())
		return
	}

	// An update that answers no body: PUT /tenants/{id}/owners/{id} is a 200
	// and nothing, every time. Unmarshalling that is "Error parsing response"
	// AFTER the server has already accepted the change -- so the write looks
	// like a failure and the new value never reaches state.
	if len(respBody) == 0 {
		respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/lifecycle/%v", state.Name.ValueString()), nil)
		if err != nil {
			resp.Diagnostics.AddError("Error reading back the updated lifecycle", err.Error())
			return
		}
	}

	if len(respBody) > 0 {
		var result client.LifecycleDocument
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated lifecycle resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *LifecycleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state LifecycleModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/lifecycle/%v", state.Name.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting lifecycle", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted lifecycle resource")
}

func (r *LifecycleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("name"), req, resp)
}
