// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// LifecycleModel is the Terraform model for lifecycle.
type LifecycleModel struct {
	Type types.String `tfsdk:"type"`
	Initial jsontypes.Normalized `tfsdk:"initial"`
	Active jsontypes.Normalized `tfsdk:"active"`
	Inactive jsontypes.Normalized `tfsdk:"inactive"`
	Defaults jsontypes.Normalized `tfsdk:"defaults"`
	Transitions jsontypes.Normalized `tfsdk:"transitions"`
	Rights jsontypes.Normalized `tfsdk:"rights"`
	Actions jsontypes.Normalized `tfsdk:"actions"`
	Colors jsontypes.Normalized `tfsdk:"colors"`
	Name types.String `tfsdk:"name"`
	CanonicalCase jsontypes.Normalized `tfsdk:"canonical_case"`
	Url types.String `tfsdk:"url"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *LifecycleModel) ToClientModel() (*client.LifecyclesPostRequest, error) {
	out := &client.LifecyclesPostRequest{}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *LifecycleModel) ToUpdateModel() (*client.LifecycleConfiguration, error) {
	out := &client.LifecycleConfiguration{}
	if !m.Type.IsNull() && !m.Type.IsUnknown() {
		out.Type = m.Type.ValueString()
	}
	if !m.Initial.IsNull() && !m.Initial.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Initial.ValueString()), &out.Initial); err != nil {
			return out, fmt.Errorf("initial: %w", err)
		}
	}
	if !m.Active.IsNull() && !m.Active.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Active.ValueString()), &out.Active); err != nil {
			return out, fmt.Errorf("active: %w", err)
		}
	}
	if !m.Inactive.IsNull() && !m.Inactive.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Inactive.ValueString()), &out.Inactive); err != nil {
			return out, fmt.Errorf("inactive: %w", err)
		}
	}
	if !m.Defaults.IsNull() && !m.Defaults.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Defaults.ValueString()), &out.Defaults); err != nil {
			return out, fmt.Errorf("defaults: %w", err)
		}
	}
	if !m.Transitions.IsNull() && !m.Transitions.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Transitions.ValueString()), &out.Transitions); err != nil {
			return out, fmt.Errorf("transitions: %w", err)
		}
	}
	if !m.Rights.IsNull() && !m.Rights.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Rights.ValueString()), &out.Rights); err != nil {
			return out, fmt.Errorf("rights: %w", err)
		}
	}
	if !m.Actions.IsNull() && !m.Actions.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Actions.ValueString()), &out.Actions); err != nil {
			return out, fmt.Errorf("actions: %w", err)
		}
	}
	if !m.Colors.IsNull() && !m.Colors.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Colors.ValueString()), &out.Colors); err != nil {
			return out, fmt.Errorf("colors: %w", err)
		}
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *LifecycleModel) FromClientModel(c *client.LifecycleDocument) {
	m.Type = types.StringValue(c.Type)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Initial); err == nil {
		if m.Initial.IsNull() || m.Initial.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Initial.ValueString()) {
			m.Initial = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Active); err == nil {
		if m.Active.IsNull() || m.Active.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Active.ValueString()) {
			m.Active = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Inactive); err == nil {
		if m.Inactive.IsNull() || m.Inactive.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Inactive.ValueString()) {
			m.Inactive = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Defaults); err == nil {
		if m.Defaults.IsNull() || m.Defaults.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Defaults.ValueString()) {
			m.Defaults = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Transitions); err == nil {
		if m.Transitions.IsNull() || m.Transitions.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Transitions.ValueString()) {
			m.Transitions = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Rights); err == nil {
		if m.Rights.IsNull() || m.Rights.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Rights.ValueString()) {
			m.Rights = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Actions); err == nil {
		if m.Actions.IsNull() || m.Actions.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Actions.ValueString()) {
			m.Actions = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Colors); err == nil {
		if m.Colors.IsNull() || m.Colors.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Colors.ValueString()) {
			m.Colors = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Name = types.StringValue(c.Name)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.CanonicalCase); err == nil {
		if m.CanonicalCase.IsNull() || m.CanonicalCase.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.CanonicalCase.ValueString()) {
			m.CanonicalCase = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Url = types.StringValue(c.Url)
}
