// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ provider.Provider = &rtProvider{}

type rtProvider struct {
	version string
}

type rtProviderModel struct {
	Endpoint types.String `tfsdk:"endpoint"`
	ApiKey   types.String `tfsdk:"api_key"`
	Token    types.String `tfsdk:"token"`
	Username types.String `tfsdk:"username"`
	Password types.String `tfsdk:"password"`
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &rtProvider{
			version: version,
		}
	}
}

func (p *rtProvider) Metadata(_ context.Context, _ provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "rt"
	resp.Version = p.version
}

func (p *rtProvider) Schema(_ context.Context, _ provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"endpoint": schema.StringAttribute{
				Optional:    true,
				Description: "The API endpoint URL.",
			},
			"api_key": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "The API key for authentication.",
			},
			"token": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "The bearer token for authentication.",
			},
			"username": schema.StringAttribute{
				Optional:    true,
				Description: "The username for basic authentication.",
			},
			"password": schema.StringAttribute{
				Optional:    true,
				Sensitive:   true,
				Description: "The password for basic authentication.",
			},
		},
	}
}

func (p *rtProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var config rtProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if config.Endpoint.IsUnknown() {
		resp.Diagnostics.AddWarning(
			"Unknown Endpoint Value",
			"The provider endpoint value is not yet known. Defaulting to the spec-defined base path.",
		)
	}

	endpoint := "/REST/2.0"
	if !config.Endpoint.IsNull() && !config.Endpoint.IsUnknown() {
		endpoint = config.Endpoint.ValueString()
	}

	c := client.NewClient(endpoint)

	if !config.ApiKey.IsNull() {
		c.ApiKey = config.ApiKey.ValueString()
	}
	if !config.Token.IsNull() {
		c.Token = config.Token.ValueString()
	}
	if !config.Username.IsNull() {
		c.Username = config.Username.ValueString()
	}
	if !config.Password.IsNull() {
		c.Password = config.Password.ValueString()
	}

	resp.DataSourceData = c
	resp.ResourceData = c
}

func (p *rtProvider) Resources(_ context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewArticleResource,
		NewAssetResource,
		NewCatalogResource,
		NewCatalogRightResource,
		NewClassResource,
		NewClassRightResource,
		NewCustomfieldResource,
		NewCustomfieldAppliestoResource,
		NewCustomfieldRightResource,
		NewCustomfieldValueResource,
		NewGlobalRightResource,
		NewGroupResource,
		NewGroupMemberResource,
		NewGroupRightResource,
		NewLifecycleResource,
		NewLifecycleMapResource,
		NewQueueResource,
		NewQueueRightResource,
		NewTicketResource,
		NewUserResource,
		NewUserGroupResource,
	}
}

func (p *rtProvider) DataSources(_ context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewArticleDataSource,
		NewAssetDataSource,
		NewCatalogDataSource,
		NewCatalogRightDataSource,
		NewClassDataSource,
		NewClassRightDataSource,
		NewCustomfieldDataSource,
		NewCustomfieldAppliestoDataSource,
		NewCustomfieldRightDataSource,
		NewCustomfieldValueDataSource,
		NewGlobalRightDataSource,
		NewGroupDataSource,
		NewGroupMemberDataSource,
		NewGroupRightDataSource,
		NewLifecycleDataSource,
		NewLifecycleMapDataSource,
		NewQueueDataSource,
		NewQueueRightDataSource,
		NewTicketDataSource,
		NewUserDataSource,
		NewUserGroupDataSource,
	}
}
