// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// QueueModel is the Terraform model for queue.
type QueueModel struct {
	Id types.String `tfsdk:"id"`
	Created types.String `tfsdk:"created"`
	Creator jsontypes.Normalized `tfsdk:"creator"`
	LastUpdated types.String `tfsdk:"last_updated"`
	LastUpdatedBy jsontypes.Normalized `tfsdk:"last_updated_by"`
	CustomFields jsontypes.Normalized `tfsdk:"custom_fields"`
	SLADisabled types.String `tfsdk:"sla_disabled"`
	Cc jsontypes.Normalized `tfsdk:"cc"`
	AdminCc jsontypes.Normalized `tfsdk:"admin_cc"`
	SortOrder types.String `tfsdk:"sort_order"`
	Name types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	TicketCustomFields jsontypes.Normalized `tfsdk:"ticket_custom_fields"`
	CommentAddress types.String `tfsdk:"comment_address"`
	Disabled types.String `tfsdk:"disabled"`
	Lifecycle types.String `tfsdk:"api_lifecycle"`
	Hyperlinks jsontypes.Normalized `tfsdk:"hyperlinks"`
	CorrespondAddress types.String `tfsdk:"correspond_address"`
	TicketTransactionCustomFields jsontypes.Normalized `tfsdk:"ticket_transaction_custom_fields"`
	SubjectTag types.String `tfsdk:"subject_tag"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *QueueModel) ToClientModel() (*client.QueuePostRequest, error) {
	out := &client.QueuePostRequest{}
	if !m.SLADisabled.IsNull() && !m.SLADisabled.IsUnknown() {
		out.SLADisabled = m.SLADisabled.ValueString()
	}
	if !m.SortOrder.IsNull() && !m.SortOrder.IsUnknown() {
		out.SortOrder = m.SortOrder.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.CommentAddress.IsNull() && !m.CommentAddress.IsUnknown() {
		out.CommentAddress = m.CommentAddress.ValueString()
	}
	if !m.Disabled.IsNull() && !m.Disabled.IsUnknown() {
		out.Disabled = m.Disabled.ValueString()
	}
	if !m.Lifecycle.IsNull() && !m.Lifecycle.IsUnknown() {
		out.Lifecycle = m.Lifecycle.ValueString()
	}
	if !m.CorrespondAddress.IsNull() && !m.CorrespondAddress.IsUnknown() {
		out.CorrespondAddress = m.CorrespondAddress.ValueString()
	}
	if !m.SubjectTag.IsNull() && !m.SubjectTag.IsUnknown() {
		out.SubjectTag = m.SubjectTag.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *QueueModel) ToUpdateModel() (*client.QueueIdNamePutRequest, error) {
	out := &client.QueueIdNamePutRequest{}
	if !m.SLADisabled.IsNull() && !m.SLADisabled.IsUnknown() {
		out.SLADisabled = m.SLADisabled.ValueString()
	}
	if !m.SortOrder.IsNull() && !m.SortOrder.IsUnknown() {
		out.SortOrder = m.SortOrder.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Description.IsNull() && !m.Description.IsUnknown() {
		out.Description = m.Description.ValueString()
	}
	if !m.CommentAddress.IsNull() && !m.CommentAddress.IsUnknown() {
		out.CommentAddress = m.CommentAddress.ValueString()
	}
	if !m.Disabled.IsNull() && !m.Disabled.IsUnknown() {
		out.Disabled = m.Disabled.ValueString()
	}
	if !m.Lifecycle.IsNull() && !m.Lifecycle.IsUnknown() {
		out.Lifecycle = m.Lifecycle.ValueString()
	}
	if !m.CorrespondAddress.IsNull() && !m.CorrespondAddress.IsUnknown() {
		out.CorrespondAddress = m.CorrespondAddress.ValueString()
	}
	if !m.SubjectTag.IsNull() && !m.SubjectTag.IsUnknown() {
		out.SubjectTag = m.SubjectTag.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *QueueModel) FromClientModel(c *client.QueueIdNameGet200Response) {
	m.Id = types.StringValue(string(c.Id))
	m.Created = types.StringValue(c.Created)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Creator); err == nil {
		if m.Creator.IsNull() || m.Creator.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Creator.ValueString()) {
			m.Creator = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.LastUpdated = types.StringValue(c.LastUpdated)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LastUpdatedBy); err == nil {
		if m.LastUpdatedBy.IsNull() || m.LastUpdatedBy.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LastUpdatedBy.ValueString()) {
			m.LastUpdatedBy = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.CustomFields); err == nil {
		if m.CustomFields.IsNull() || m.CustomFields.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.CustomFields.ValueString()) {
			m.CustomFields = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.SLADisabled = types.StringValue(c.SLADisabled)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Cc); err == nil {
		if m.Cc.IsNull() || m.Cc.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Cc.ValueString()) {
			m.Cc = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.AdminCc); err == nil {
		if m.AdminCc.IsNull() || m.AdminCc.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.AdminCc.ValueString()) {
			m.AdminCc = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.SortOrder = types.StringValue(c.SortOrder)
	m.Name = types.StringValue(c.Name)
	m.Description = types.StringValue(c.Description)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.TicketCustomFields); err == nil {
		if m.TicketCustomFields.IsNull() || m.TicketCustomFields.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.TicketCustomFields.ValueString()) {
			m.TicketCustomFields = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.CommentAddress = types.StringValue(c.CommentAddress)
	m.Disabled = types.StringValue(c.Disabled)
	m.Lifecycle = types.StringValue(c.Lifecycle)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Hyperlinks); err == nil {
		if m.Hyperlinks.IsNull() || m.Hyperlinks.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Hyperlinks.ValueString()) {
			m.Hyperlinks = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.CorrespondAddress = types.StringValue(c.CorrespondAddress)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.TicketTransactionCustomFields); err == nil {
		if m.TicketTransactionCustomFields.IsNull() || m.TicketTransactionCustomFields.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.TicketTransactionCustomFields.ValueString()) {
			m.TicketTransactionCustomFields = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.SubjectTag = types.StringValue(c.SubjectTag)
}
