// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ datasource.DataSource = &QueueDataSource{}

func NewQueueDataSource() datasource.DataSource {
	return &QueueDataSource{}
}

type QueueDataSource struct {
	client *client.Client
}

func (d *QueueDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_queue"
}

func (d *QueueDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a queue data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Integer identifier",
			},
			"created": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"creator": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"last_updated": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"last_updated_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"custom_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Customfields with their values, as returned by the server.",
			},
			"sla_disabled": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"cc": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"admin_cc": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"sort_order": schema.StringAttribute{
				Computed:    true,
				Description: "Seems to be an enumeration of some kind.",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"ticket_custom_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "The custom fields applied to an object, as a queue lists the ones its tickets have. No values -- these are the fields themselves.",
			},
			"comment_address": schema.StringAttribute{
				Computed:    true,
				Description: "May be empty.",
			},
			"disabled": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"api_lifecycle": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"hyperlinks": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Things and operations related to this queue.",
			},
			"correspond_address": schema.StringAttribute{
				Computed:    true,
				Description: "Reply Address in the UI",
			},
			"ticket_transaction_custom_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "TODO",
			},
			"subject_tag": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
		},
	}
}

func (d *QueueDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *QueueDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config QueueModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/queue/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading queue", err.Error())
		return
	}

	var result client.QueueIdNameGet200Response
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read queue data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
