// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"encoding/json"



	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"

	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"



	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ resource.Resource = &TicketResource{}
var _ resource.ResourceWithImportState = &TicketResource{}

func NewTicketResource() resource.Resource {
	return &TicketResource{}
}

type TicketResource struct {
	client *client.Client
}

func (r *TicketResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ticket"
}

func (r *TicketResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Manages a ticket resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Integer identifier",
			},
			"created": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"creator": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"last_updated": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"last_updated_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"custom_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "Customfields with their values, as returned by the server.",
			},
			"queue": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Required:    true,
				Description: "",
			},
			"owner": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"starts": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"started": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"effective_id": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"resolved": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"due": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"subject": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"time_estimated": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"time_worked": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"time_left": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"initial_priority": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"priority": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "Ticket priority as an integer from 0 (low) to 100 (high)",
			},
			"final_priority": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"requestor": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "",
			},
			"cc": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "probably userReferences",
			},
			"admin_cc": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Optional:    true,
				Description: "probably userReferences",
			},
			"type": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Description: "The values of this field depend on the lifecycle in use.",
			},
			"hyperlinks": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Things and operations related to this ticket. Probably contains multiple lifecycle operations.",
			},
			"api_depends_on": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"child": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"referred_to_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"parent": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"depended_on_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"refers_to": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Optional:    true,
				Description: "",
			},
			"content": schema.StringAttribute{
				Optional:    true,
				Description: "The first message of the ticket",
			},
		},
	}
}

func (r *TicketResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	r.client = c
}

func (r *TicketResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan TicketModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	reqBody, err := plan.ToClientModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid ticket configuration", err.Error())
		return
	}

	respBody, location, err := r.client.DoCreateRequest(ctx, "POST", "/ticket", reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error creating ticket", err.Error())
		return
	}

	// RT's create answers a 201 whose body is an identifier and a link, not
	// the resource -- and sometimes only a Location header. Either way what
	// was created has to be READ BACK, not taken from the create's own
	// answer: taking it wrote empty strings over the values just sent,
	// "provider produced inconsistent result after apply".
	if created := client.IDFromCreate(respBody, location); created != "" {
		plan.Id = types.StringValue(created)
	}

	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/ticket/%v", plan.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the created ticket", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.TicketIdGet200Response
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "created ticket resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *TicketResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state TicketModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// A resource with no identifier is not a resource. Without this the read
	// interpolates an empty id and asks the COLLECTION endpoint, which answers
	// 200 and a list -- so a state written before the id was known would look
	// healthy forever instead of being adopted again.
	if state.Id.ValueString() == "" {
		resp.State.RemoveResource(ctx)
		return
	}

	respBody, err := r.client.DoRequest(ctx, "GET", fmt.Sprintf("/ticket/%v", state.Id.ValueString()), nil)
	if err != nil {
		// GONE IS NOT BROKEN. A 404 here means the resource this state row
		// describes no longer exists -- deleted by hand, or by something else
		// that owns it -- and the honest answer is to drop the row and let the
		// plan decide whether to recreate it. Raising instead fails every plan
		// in the configuration, including the ones with nothing to do with this
		// resource, and leaves no way out but editing state by hand.
		//
		// ONLY IN Read. The same 404 after a create or an update is a real
		// failure: something we just wrote is missing.
		var apiErr *client.APIError
		if errors.As(err, &apiErr) && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Error reading ticket", err.Error())
		return
	}

	var result client.TicketIdGet200Response
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	state.FromClientModel(&result)

	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *TicketResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan TicketModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The identifiers come off state: they cannot change on an update, and the
	// plan's copy of a Computed one is unknown -- which is also the only place
	// an imported nested resource's parents live.
	var state TicketModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// The UPDATE model, not the create one -- see ToUpdateModel.
	reqBody, err := plan.ToUpdateModel()
	if err != nil {
		resp.Diagnostics.AddError("Invalid ticket configuration", err.Error())
		return
	}

	respBody, err := r.client.DoRequest(ctx, "PUT", fmt.Sprintf("/ticket/%v", state.Id.ValueString()), reqBody)
	if err != nil {
		resp.Diagnostics.AddError("Error updating ticket", err.Error())
		return
	}

	// AN UPDATE'S ANSWER IS NOT THE READ'S. RT answers a PUT with the list of
	// changes it made -- ["Description changed from 'a' to 'b'"] -- and some
	// updates answer nothing at all; neither is the resource, and
	// unmarshalling either one is "Error parsing response" AFTER the server
	// has already accepted the change. What it now looks like is read back.
	respBody, err = r.client.DoRequest(ctx, "GET", fmt.Sprintf("/ticket/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading back the updated ticket", err.Error())
		return
	}

	if len(respBody) > 0 {
		var result client.TicketIdGet200Response
		if err := json.Unmarshal(respBody, &result); err != nil {
			resp.Diagnostics.AddError("Error parsing response", err.Error())
			return
		}

		plan.FromClientModel(&result)
	}

	tflog.Trace(ctx, "updated ticket resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *TicketResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state TicketModel

	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.DoRequest(ctx, "DELETE", fmt.Sprintf("/ticket/%v", state.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error deleting ticket", err.Error())
		return
	}

	tflog.Trace(ctx, "deleted ticket resource")
}

func (r *TicketResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
