// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// TicketModel is the Terraform model for ticket.
type TicketModel struct {
	Id types.String `tfsdk:"id"`
	Created types.String `tfsdk:"created"`
	Creator jsontypes.Normalized `tfsdk:"creator"`
	LastUpdated types.String `tfsdk:"last_updated"`
	LastUpdatedBy jsontypes.Normalized `tfsdk:"last_updated_by"`
	CustomFields jsontypes.Normalized `tfsdk:"custom_fields"`
	Queue jsontypes.Normalized `tfsdk:"queue"`
	Owner jsontypes.Normalized `tfsdk:"owner"`
	Starts types.String `tfsdk:"starts"`
	Started types.String `tfsdk:"started"`
	EffectiveId jsontypes.Normalized `tfsdk:"effective_id"`
	Resolved types.String `tfsdk:"resolved"`
	Due types.String `tfsdk:"due"`
	Subject types.String `tfsdk:"subject"`
	TimeEstimated types.String `tfsdk:"time_estimated"`
	TimeWorked types.String `tfsdk:"time_worked"`
	TimeLeft types.String `tfsdk:"time_left"`
	InitialPriority types.String `tfsdk:"initial_priority"`
	Priority types.String `tfsdk:"priority"`
	FinalPriority types.String `tfsdk:"final_priority"`
	Requestor jsontypes.Normalized `tfsdk:"requestor"`
	Cc jsontypes.Normalized `tfsdk:"cc"`
	AdminCc jsontypes.Normalized `tfsdk:"admin_cc"`
	Type types.String `tfsdk:"type"`
	Status types.String `tfsdk:"status"`
	Hyperlinks jsontypes.Normalized `tfsdk:"hyperlinks"`
	DependsOn jsontypes.Normalized `tfsdk:"api_depends_on"`
	Child jsontypes.Normalized `tfsdk:"child"`
	ReferredToBy jsontypes.Normalized `tfsdk:"referred_to_by"`
	Parent jsontypes.Normalized `tfsdk:"parent"`
	DependedOnBy jsontypes.Normalized `tfsdk:"depended_on_by"`
	RefersTo jsontypes.Normalized `tfsdk:"refers_to"`
	Content types.String `tfsdk:"content"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *TicketModel) ToClientModel() (*client.TicketPostRequest, error) {
	out := &client.TicketPostRequest{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.CustomFields.IsNull() && !m.CustomFields.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomFields.ValueString()), &out.CustomFields); err != nil {
			return out, fmt.Errorf("custom_fields: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Queue.IsNull() && !m.Queue.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Queue.ValueString()), &out.Queue); err != nil {
			return out, fmt.Errorf("queue: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Owner.IsNull() && !m.Owner.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Owner.ValueString()), &out.Owner); err != nil {
			return out, fmt.Errorf("owner: %w", err)
		}
	}
	if !m.Starts.IsNull() && !m.Starts.IsUnknown() {
		out.Starts = m.Starts.ValueString()
	}
	if !m.Due.IsNull() && !m.Due.IsUnknown() {
		out.Due = m.Due.ValueString()
	}
	if !m.Subject.IsNull() && !m.Subject.IsUnknown() {
		out.Subject = m.Subject.ValueString()
	}
	if !m.Priority.IsNull() && !m.Priority.IsUnknown() {
		out.Priority = m.Priority.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Requestor.IsNull() && !m.Requestor.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Requestor.ValueString()), &out.Requestor); err != nil {
			return out, fmt.Errorf("requestor: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Cc.IsNull() && !m.Cc.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Cc.ValueString()), &out.Cc); err != nil {
			return out, fmt.Errorf("cc: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.AdminCc.IsNull() && !m.AdminCc.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AdminCc.ValueString()), &out.AdminCc); err != nil {
			return out, fmt.Errorf("admin_cc: %w", err)
		}
	}
	if !m.Status.IsNull() && !m.Status.IsUnknown() {
		out.Status = m.Status.ValueString()
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.DependsOn.IsNull() && !m.DependsOn.IsUnknown() {
		if err := json.Unmarshal([]byte(m.DependsOn.ValueString()), &out.DependsOn); err != nil {
			return out, fmt.Errorf("api_depends_on: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Child.IsNull() && !m.Child.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Child.ValueString()), &out.Child); err != nil {
			return out, fmt.Errorf("child: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.ReferredToBy.IsNull() && !m.ReferredToBy.IsUnknown() {
		if err := json.Unmarshal([]byte(m.ReferredToBy.ValueString()), &out.ReferredToBy); err != nil {
			return out, fmt.Errorf("referred_to_by: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.Parent.IsNull() && !m.Parent.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Parent.ValueString()), &out.Parent); err != nil {
			return out, fmt.Errorf("parent: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.DependedOnBy.IsNull() && !m.DependedOnBy.IsUnknown() {
		if err := json.Unmarshal([]byte(m.DependedOnBy.ValueString()), &out.DependedOnBy); err != nil {
			return out, fmt.Errorf("depended_on_by: %w", err)
		}
	}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.RefersTo.IsNull() && !m.RefersTo.IsUnknown() {
		if err := json.Unmarshal([]byte(m.RefersTo.ValueString()), &out.RefersTo); err != nil {
			return out, fmt.Errorf("refers_to: %w", err)
		}
	}
	if !m.Content.IsNull() && !m.Content.IsUnknown() {
		out.Content = m.Content.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *TicketModel) ToUpdateModel() (*client.TicketIdPutRequest, error) {
	out := &client.TicketIdPutRequest{}
	if !m.CustomFields.IsNull() && !m.CustomFields.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomFields.ValueString()), &out.CustomFields); err != nil {
			return out, fmt.Errorf("custom_fields: %w", err)
		}
	}
	if !m.Queue.IsNull() && !m.Queue.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Queue.ValueString()), &out.Queue); err != nil {
			return out, fmt.Errorf("queue: %w", err)
		}
	}
	if !m.Owner.IsNull() && !m.Owner.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Owner.ValueString()), &out.Owner); err != nil {
			return out, fmt.Errorf("owner: %w", err)
		}
	}
	if !m.Starts.IsNull() && !m.Starts.IsUnknown() {
		out.Starts = m.Starts.ValueString()
	}
	if !m.Due.IsNull() && !m.Due.IsUnknown() {
		out.Due = m.Due.ValueString()
	}
	if !m.Subject.IsNull() && !m.Subject.IsUnknown() {
		out.Subject = m.Subject.ValueString()
	}
	if !m.Priority.IsNull() && !m.Priority.IsUnknown() {
		out.Priority = m.Priority.ValueString()
	}
	if !m.Requestor.IsNull() && !m.Requestor.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Requestor.ValueString()), &out.Requestor); err != nil {
			return out, fmt.Errorf("requestor: %w", err)
		}
	}
	if !m.Cc.IsNull() && !m.Cc.IsUnknown() {
		if err := json.Unmarshal([]byte(m.Cc.ValueString()), &out.Cc); err != nil {
			return out, fmt.Errorf("cc: %w", err)
		}
	}
	if !m.AdminCc.IsNull() && !m.AdminCc.IsUnknown() {
		if err := json.Unmarshal([]byte(m.AdminCc.ValueString()), &out.AdminCc); err != nil {
			return out, fmt.Errorf("admin_cc: %w", err)
		}
	}
	if !m.Status.IsNull() && !m.Status.IsUnknown() {
		out.Status = m.Status.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *TicketModel) FromClientModel(c *client.TicketIdGet200Response) {
	m.Id = types.StringValue(string(c.Id))
	m.Created = types.StringValue(c.Created)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Creator); err == nil {
		if m.Creator.IsNull() || m.Creator.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Creator.ValueString()) {
			m.Creator = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.LastUpdated = types.StringValue(c.LastUpdated)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LastUpdatedBy); err == nil {
		if m.LastUpdatedBy.IsNull() || m.LastUpdatedBy.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LastUpdatedBy.ValueString()) {
			m.LastUpdatedBy = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.CustomFields.IsUnknown() {
		m.CustomFields = jsontypes.NewNormalizedNull()
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Owner.IsUnknown() {
		m.Owner = jsontypes.NewNormalizedNull()
	}
	m.Starts = types.StringValue(c.Starts)
	m.Started = types.StringValue(c.Started)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.EffectiveId); err == nil {
		if m.EffectiveId.IsNull() || m.EffectiveId.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.EffectiveId.ValueString()) {
			m.EffectiveId = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.Resolved = types.StringValue(c.Resolved)
	m.Due = types.StringValue(c.Due)
	m.Subject = types.StringValue(c.Subject)
	m.TimeEstimated = types.StringValue(c.TimeEstimated)
	m.TimeWorked = types.StringValue(c.TimeWorked)
	m.TimeLeft = types.StringValue(c.TimeLeft)
	m.InitialPriority = types.StringValue(c.InitialPriority)
	m.Priority = types.StringValue(c.Priority)
	m.FinalPriority = types.StringValue(c.FinalPriority)
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Requestor.IsUnknown() {
		m.Requestor = jsontypes.NewNormalizedNull()
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.Cc.IsUnknown() {
		m.Cc = jsontypes.NewNormalizedNull()
	}
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.AdminCc.IsUnknown() {
		m.AdminCc = jsontypes.NewNormalizedNull()
	}
	m.Type = types.StringValue(c.Type)
	m.Status = types.StringValue(c.Status)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Hyperlinks); err == nil {
		if m.Hyperlinks.IsNull() || m.Hyperlinks.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Hyperlinks.ValueString()) {
			m.Hyperlinks = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
