// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ datasource.DataSource = &TicketDataSource{}

func NewTicketDataSource() datasource.DataSource {
	return &TicketDataSource{}
}

type TicketDataSource struct {
	client *client.Client
}

func (d *TicketDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ticket"
}

func (d *TicketDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a ticket data source.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Integer identifier",
			},
			"created": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"creator": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"last_updated": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"last_updated_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"custom_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Customfields with their values, as returned by the server.",
			},
			"queue": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Required:    true,
				Description: "",
			},
			"owner": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"starts": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"started": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"effective_id": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"resolved": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"due": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"subject": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"time_estimated": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"time_worked": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"time_left": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"initial_priority": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"priority": schema.StringAttribute{
				Computed:    true,
				Description: "Ticket priority as an integer from 0 (low) to 100 (high)",
			},
			"final_priority": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"requestor": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"cc": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "probably userReferences",
			},
			"admin_cc": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "probably userReferences",
			},
			"type": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Description: "The values of this field depend on the lifecycle in use.",
			},
			"_hyperlinks": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Things and operations related to this ticket. Probably contains multiple lifecycle operations.",
			},
			"api_depends_on": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"child": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"referred_to_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"parent": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"depended_on_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"refers_to": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"content": schema.StringAttribute{
				Computed:    true,
				Description: "The first message of the ticket",
			},
		},
	}
}

func (d *TicketDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *TicketDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config TicketModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/ticket/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading ticket", err.Error())
		return
	}

	var result client.TicketIdGet200Response
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read ticket data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
