// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// UserGroupModel is the Terraform model for user_group.
type UserGroupModel struct {
	IdOrName types.String `tfsdk:"id_or_name"`
}



