// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"encoding/json"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

// UserModel is the Terraform model for user.
type UserModel struct {
	CustomFields jsontypes.Normalized `tfsdk:"custom_fields"`
	Id types.String `tfsdk:"id"`
	Created types.String `tfsdk:"created"`
	Creator jsontypes.Normalized `tfsdk:"creator"`
	LastUpdated types.String `tfsdk:"last_updated"`
	LastUpdatedBy jsontypes.Normalized `tfsdk:"last_updated_by"`
	RealName types.String `tfsdk:"real_name"`
	NickName types.String `tfsdk:"nick_name"`
	EmailAddress types.String `tfsdk:"email_address"`
	Gecos types.String `tfsdk:"gecos"`
	Lang types.String `tfsdk:"lang"`
	Timezone types.String `tfsdk:"timezone"`
	FreeformContactInfo types.String `tfsdk:"freeform_contact_info"`
	Comments types.String `tfsdk:"comments"`
	WorkPhone types.String `tfsdk:"work_phone"`
	MobilePhone types.String `tfsdk:"mobile_phone"`
	HomePhone types.String `tfsdk:"home_phone"`
	PagerPhone types.String `tfsdk:"pager_phone"`
	Organization types.String `tfsdk:"organization"`
	Address1 types.String `tfsdk:"address1"`
	Address2 types.String `tfsdk:"address2"`
	City types.String `tfsdk:"city"`
	Zip types.String `tfsdk:"zip"`
	State types.String `tfsdk:"state"`
	Country types.String `tfsdk:"country"`
	Name types.String `tfsdk:"name"`
	Disabled types.String `tfsdk:"disabled"`
	Privileged types.String `tfsdk:"privileged"`
	Memberships jsontypes.Normalized `tfsdk:"memberships"`
	Hyperlinks jsontypes.Normalized `tfsdk:"_hyperlinks"`
	Password types.String `tfsdk:"password"`
}

// ToClientModel converts a Terraform model to a client model.
func (m *UserModel) ToClientModel() (*client.UserPostRequest, error) {
	out := &client.UserPostRequest{}
	// A silently dropped field is worse than a loud one: bad JSON here means
	// the configuration said something this resource cannot send, and the
	// request would otherwise go out quietly missing it.
	if !m.CustomFields.IsNull() && !m.CustomFields.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomFields.ValueString()), &out.CustomFields); err != nil {
			return out, fmt.Errorf("custom_fields: %w", err)
		}
	}
	if !m.RealName.IsNull() && !m.RealName.IsUnknown() {
		out.RealName = m.RealName.ValueString()
	}
	if !m.NickName.IsNull() && !m.NickName.IsUnknown() {
		out.NickName = m.NickName.ValueString()
	}
	if !m.EmailAddress.IsNull() && !m.EmailAddress.IsUnknown() {
		out.EmailAddress = m.EmailAddress.ValueString()
	}
	if !m.Gecos.IsNull() && !m.Gecos.IsUnknown() {
		out.Gecos = m.Gecos.ValueString()
	}
	if !m.Lang.IsNull() && !m.Lang.IsUnknown() {
		out.Lang = m.Lang.ValueString()
	}
	if !m.Timezone.IsNull() && !m.Timezone.IsUnknown() {
		out.Timezone = m.Timezone.ValueString()
	}
	if !m.FreeformContactInfo.IsNull() && !m.FreeformContactInfo.IsUnknown() {
		out.FreeformContactInfo = m.FreeformContactInfo.ValueString()
	}
	if !m.Comments.IsNull() && !m.Comments.IsUnknown() {
		out.Comments = m.Comments.ValueString()
	}
	if !m.WorkPhone.IsNull() && !m.WorkPhone.IsUnknown() {
		out.WorkPhone = m.WorkPhone.ValueString()
	}
	if !m.MobilePhone.IsNull() && !m.MobilePhone.IsUnknown() {
		out.MobilePhone = m.MobilePhone.ValueString()
	}
	if !m.HomePhone.IsNull() && !m.HomePhone.IsUnknown() {
		out.HomePhone = m.HomePhone.ValueString()
	}
	if !m.PagerPhone.IsNull() && !m.PagerPhone.IsUnknown() {
		out.PagerPhone = m.PagerPhone.ValueString()
	}
	if !m.Organization.IsNull() && !m.Organization.IsUnknown() {
		out.Organization = m.Organization.ValueString()
	}
	if !m.Address1.IsNull() && !m.Address1.IsUnknown() {
		out.Address1 = m.Address1.ValueString()
	}
	if !m.Address2.IsNull() && !m.Address2.IsUnknown() {
		out.Address2 = m.Address2.ValueString()
	}
	if !m.City.IsNull() && !m.City.IsUnknown() {
		out.City = m.City.ValueString()
	}
	if !m.Zip.IsNull() && !m.Zip.IsUnknown() {
		out.Zip = m.Zip.ValueString()
	}
	if !m.State.IsNull() && !m.State.IsUnknown() {
		out.State = m.State.ValueString()
	}
	if !m.Country.IsNull() && !m.Country.IsUnknown() {
		out.Country = m.Country.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	if !m.Password.IsNull() && !m.Password.IsUnknown() {
		out.Password = m.Password.ValueString()
	}
	return out, nil
}

// ToUpdateModel converts a Terraform model to the UPDATE client model, which is
// a different shape from the create one: RT's update bodies have no
// inboundProtocolConfiguration and no id, and sending the create model to the
// patch endpoint is answered with "provided request body content is not in the
// expected format".
//
// Fields the patch model does not declare are simply absent here -- the
// generator only emits the ones it has.
func (m *UserModel) ToUpdateModel() (*client.UserIdNamePutRequest, error) {
	out := &client.UserIdNamePutRequest{}
	if !m.CustomFields.IsNull() && !m.CustomFields.IsUnknown() {
		if err := json.Unmarshal([]byte(m.CustomFields.ValueString()), &out.CustomFields); err != nil {
			return out, fmt.Errorf("custom_fields: %w", err)
		}
	}
	if !m.RealName.IsNull() && !m.RealName.IsUnknown() {
		out.RealName = m.RealName.ValueString()
	}
	if !m.NickName.IsNull() && !m.NickName.IsUnknown() {
		out.NickName = m.NickName.ValueString()
	}
	if !m.EmailAddress.IsNull() && !m.EmailAddress.IsUnknown() {
		out.EmailAddress = m.EmailAddress.ValueString()
	}
	if !m.Gecos.IsNull() && !m.Gecos.IsUnknown() {
		out.Gecos = m.Gecos.ValueString()
	}
	if !m.Lang.IsNull() && !m.Lang.IsUnknown() {
		out.Lang = m.Lang.ValueString()
	}
	if !m.Timezone.IsNull() && !m.Timezone.IsUnknown() {
		out.Timezone = m.Timezone.ValueString()
	}
	if !m.FreeformContactInfo.IsNull() && !m.FreeformContactInfo.IsUnknown() {
		out.FreeformContactInfo = m.FreeformContactInfo.ValueString()
	}
	if !m.Comments.IsNull() && !m.Comments.IsUnknown() {
		out.Comments = m.Comments.ValueString()
	}
	if !m.WorkPhone.IsNull() && !m.WorkPhone.IsUnknown() {
		out.WorkPhone = m.WorkPhone.ValueString()
	}
	if !m.MobilePhone.IsNull() && !m.MobilePhone.IsUnknown() {
		out.MobilePhone = m.MobilePhone.ValueString()
	}
	if !m.HomePhone.IsNull() && !m.HomePhone.IsUnknown() {
		out.HomePhone = m.HomePhone.ValueString()
	}
	if !m.PagerPhone.IsNull() && !m.PagerPhone.IsUnknown() {
		out.PagerPhone = m.PagerPhone.ValueString()
	}
	if !m.Organization.IsNull() && !m.Organization.IsUnknown() {
		out.Organization = m.Organization.ValueString()
	}
	if !m.Address1.IsNull() && !m.Address1.IsUnknown() {
		out.Address1 = m.Address1.ValueString()
	}
	if !m.Address2.IsNull() && !m.Address2.IsUnknown() {
		out.Address2 = m.Address2.ValueString()
	}
	if !m.City.IsNull() && !m.City.IsUnknown() {
		out.City = m.City.ValueString()
	}
	if !m.Zip.IsNull() && !m.Zip.IsUnknown() {
		out.Zip = m.Zip.ValueString()
	}
	if !m.State.IsNull() && !m.State.IsUnknown() {
		out.State = m.State.ValueString()
	}
	if !m.Country.IsNull() && !m.Country.IsUnknown() {
		out.Country = m.Country.ValueString()
	}
	if !m.Name.IsNull() && !m.Name.IsUnknown() {
		out.Name = m.Name.ValueString()
	}
	return out, nil
}

// FromClientModel updates the Terraform model from a client model.
func (m *UserModel) FromClientModel(c *client.UserIdNameGet200Response) {
	// The create body takes this and no response of the same shape answers it --
	// AssociationRequest against AssociationResponse -- so nothing above writes
	// it, and a Computed attribute the configuration left out stays UNKNOWN once
	// the apply is over: "provider returned invalid result object after apply".
	// Unknown becomes null; a value the plan already knows is left alone.
	if m.CustomFields.IsUnknown() {
		m.CustomFields = jsontypes.NewNormalizedNull()
	}
	m.Id = types.StringValue(string(c.Id))
	m.Created = types.StringValue(c.Created)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Creator); err == nil {
		if m.Creator.IsNull() || m.Creator.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Creator.ValueString()) {
			m.Creator = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.LastUpdated = types.StringValue(c.LastUpdated)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.LastUpdatedBy); err == nil {
		if m.LastUpdatedBy.IsNull() || m.LastUpdatedBy.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.LastUpdatedBy.ValueString()) {
			m.LastUpdatedBy = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	m.RealName = types.StringValue(c.RealName)
	m.NickName = types.StringValue(c.NickName)
	m.EmailAddress = types.StringValue(c.EmailAddress)
	m.Gecos = types.StringValue(c.Gecos)
	m.Lang = types.StringValue(c.Lang)
	m.Timezone = types.StringValue(c.Timezone)
	m.FreeformContactInfo = types.StringValue(c.FreeformContactInfo)
	m.Comments = types.StringValue(c.Comments)
	m.WorkPhone = types.StringValue(c.WorkPhone)
	m.MobilePhone = types.StringValue(c.MobilePhone)
	m.HomePhone = types.StringValue(c.HomePhone)
	m.PagerPhone = types.StringValue(c.PagerPhone)
	m.Organization = types.StringValue(c.Organization)
	m.Address1 = types.StringValue(c.Address1)
	m.Address2 = types.StringValue(c.Address2)
	m.City = types.StringValue(c.City)
	m.Zip = types.StringValue(c.Zip)
	m.State = types.StringValue(c.State)
	m.Country = types.StringValue(c.Country)
	m.Name = types.StringValue(c.Name)
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Memberships); err == nil {
		if m.Memberships.IsNull() || m.Memberships.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Memberships.ValueString()) {
			m.Memberships = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
	// Marshalling a Go value cannot fail in a way worth surfacing here; an
	// unrepresentable one would have failed on the way in.
	//
	// The answer is only written when it says something the configuration does
	// not already say -- see jsonSupersetOf. A server that merely filled in its
	// own defaults has told us nothing, and recording it would fail the apply
	// and then propose an update forever.
	if encoded, err := json.Marshal(c.Hyperlinks); err == nil {
		if m.Hyperlinks.IsNull() || m.Hyperlinks.IsUnknown() ||
			!jsonSupersetOf(string(encoded), m.Hyperlinks.ValueString()) {
			m.Hyperlinks = jsontypes.NewNormalizedValue(string(encoded))
		}
	}
}
