// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"encoding/json"


	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/n-at-han-k/terraform-provider-rt/internal/client"
)

var _ datasource.DataSource = &UserDataSource{}

func NewUserDataSource() datasource.DataSource {
	return &UserDataSource{}
}

type UserDataSource struct {
	client *client.Client
}

func (d *UserDataSource) Metadata(_ context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_user"
}

func (d *UserDataSource) Schema(_ context.Context, _ datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Description: "Fetches a user data source.",
		Attributes: map[string]schema.Attribute{
			"custom_fields": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "Customfields with their values, as returned by the server.",
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: "Integer identifier",
			},
			"created": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"creator": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"last_updated": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"last_updated_by": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"real_name": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"nick_name": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"email_address": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"gecos": schema.StringAttribute{
				Computed:    true,
				Description: "\"Unix login\" in the UI",
			},
			"lang": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"timezone": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"freeform_contact_info": schema.StringAttribute{
				Computed:    true,
				Description: "\"Extra info\" in the UI",
			},
			"comments": schema.StringAttribute{
				Computed:    true,
				Description: "Comments about the user.",
			},
			"work_phone": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"mobile_phone": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"home_phone": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"pager_phone": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"organization": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"address1": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"address2": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"city": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"zip": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"state": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"country": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"name": schema.StringAttribute{
				Required:    true,
				Description: "",
			},
			"disabled": schema.StringAttribute{
				Computed:    true,
				Description: "",
			},
			"privileged": schema.Int64Attribute{
				Computed:    true,
				Description: "Can this user be granted rights in RT?",
			},
			"memberships": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"hyperlinks": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: "",
			},
			"password": schema.StringAttribute{
				Computed:    true,
				Description: "Use a strong password!",
			},
		},
	}
}

func (d *UserDataSource) Configure(_ context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Data Source Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T.", req.ProviderData),
		)
		return
	}

	d.client = c
}

func (d *UserDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config UserModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	respBody, err := d.client.DoRequest(ctx, "GET", fmt.Sprintf("/user/%v", config.Id.ValueString()), nil)
	if err != nil {
		resp.Diagnostics.AddError("Error reading user", err.Error())
		return
	}

	var result client.UserIdNameGet200Response
	if err := json.Unmarshal(respBody, &result); err != nil {
		resp.Diagnostics.AddError("Error parsing response", err.Error())
		return
	}

	config.FromClientModel(&result)

	tflog.Trace(ctx, "read user data source")
	resp.Diagnostics.Append(resp.State.Set(ctx, &config)...)
}
